"""The entry contract and the per-command reconcile.

The emitted ``setup.sh``, the uv pin derived from the lock, the
rendered workflows' bare spelling, and the reconcile that re-syncs a
venv the lock has moved past. Fallbacks before happy paths
throughout: the refusals, the never-fatal failures, and the inert
states are pinned first.
"""

from __future__ import annotations

import os
import shutil
import stat
import subprocess
import sys
from pathlib import Path
from types import SimpleNamespace

import pytest

LOCK = """\
version = 1

[[package]]
name = "something"
version = "1.0.0"

[[package]]
name = "uv"
version = "0.12.7"
"""

LOCK_WITHOUT_UV = """\
version = 1

[[package]]
name = "something"
version = "1.0.0"
"""


def _contract_root(tmp_path: Path, kind: str, *, lock: str = LOCK) -> Path:
    root = tmp_path / f"contract-{kind}"
    root.mkdir(exist_ok=True)
    (root / "workshop.toml").write_text(
        "[workspace]\n"
        'layers = ["livery.workshop"]\n'
        "\n[forge]\n"
        f'kind = "{kind}"\n'
        'owner = "owner"\n'
        "\n[ci]\n"
        'runners = ["ubuntu-latest"]\n'
        'required_context = "gate"\n'
    )
    (root / "pyproject.toml").write_text(
        '[project]\nname = "scratch"\nrequires-python = ">=3.11"\n'
    )
    if lock:
        (root / "uv.lock").write_text(lock)
    return root


# --- the pin, fallbacks first ------------------------------------------------


def test_a_workspace_without_a_lock_has_no_pin(tmp_path: Path) -> None:
    from livery.workshop._entry import installer_url, locked_uv_version

    assert locked_uv_version(tmp_path) == ""
    # The unpinned installer is the honest fallback, never an
    # invented version.
    assert installer_url("") == "https://astral.sh/uv/install.sh"


def test_a_lock_without_uv_or_unreadable_has_no_pin(tmp_path: Path) -> None:
    from livery.workshop._entry import locked_uv_version

    (tmp_path / "uv.lock").write_text(LOCK_WITHOUT_UV)
    assert locked_uv_version(tmp_path) == ""
    (tmp_path / "uv.lock").write_text("not = [valid")
    assert locked_uv_version(tmp_path) == ""


def test_the_lock_pin_reaches_script_and_workflows(tmp_path: Path) -> None:
    from livery.workshop._ci_generate import generate
    from livery.workshop._entry import locked_uv_version

    root = _contract_root(tmp_path, "github")
    assert locked_uv_version(root) == "0.12.7"
    files = generate(root)
    assert "https://astral.sh/uv/0.12.7/install.sh" in files["setup.sh"]
    assert 'version: "0.12.7"' in files[".github/workflows/ci.yml"]
    gitlab = generate(_contract_root(tmp_path, "gitlab"))[".gitlab-ci.yml"]
    assert "ghcr.io/astral-sh/uv:0.12.7-python" in gitlab


# --- the rendered workflows -------------------------------------------------


def test_no_rendered_workflow_spells_uv_run(tmp_path: Path) -> None:
    from livery.workshop._ci_generate import generate

    for kind in ("github", "gitea", "gitlab"):
        for path, content in generate(_contract_root(tmp_path, kind)).items():
            if path == "setup.sh" or path == "zensical.toml":
                continue
            assert "uv run" not in content, f"{kind}: {path}"
            assert "uv sync" not in content, f"{kind}: {path}"


def test_every_forge_kind_emits_the_entry_script(tmp_path: Path) -> None:
    from livery.workshop._ci_generate import generate

    for kind in ("github", "gitea", "gitlab"):
        files = generate(_contract_root(tmp_path, kind))
        script = files["setup.sh"]
        assert "Generated by the workshop" in script
        assert "uv sync --project" in script
        assert ".workshop-sync-receipt" in script


def test_the_rung_step_precedes_the_entry_step(tmp_path: Path) -> None:
    # The entry persists the cascade into the runner's environment,
    # and a real variable outranks the shared slot: an emission taken
    # before the rung would bake committed values in over secrets.
    from livery.workshop._ci_generate import generate

    root = _contract_root(tmp_path, "gitea")
    (root / ".repo.env").write_text("SOME_KEY=value\n")
    gate = generate(root)[".gitea/workflows/ci.yml"]
    assert gate.index("Environment rung") < gate.index("setup.sh github")


def test_the_matrix_leg_selects_its_interpreter_through_the_entry(
    tmp_path: Path,
) -> None:
    from livery.workshop._ci_generate import generate

    gate = generate(_contract_root(tmp_path, "github"))[".github/workflows/ci.yml"]
    check = gate.split("  docs:")[0]
    assert "UV_PYTHON: ${{ matrix.python }}" in check
    assert "bash setup.sh github" in check


# --- the script itself, driven by bash --------------------------------------

BASH = shutil.which("bash")


def _script_home(tmp_path: Path) -> tuple[Path, Path, dict[str, str]]:
    """A rendered setup.sh beside a lock, with a stubbed PATH and HOME."""
    from livery.workshop._ci_generate import generate

    root = _contract_root(tmp_path, "github")
    (root / "setup.sh").write_text(generate(root)["setup.sh"])
    bin_dir = tmp_path / "stub-bin"
    bin_dir.mkdir(exist_ok=True)
    home = tmp_path / "stub-home"
    home.mkdir(exist_ok=True)
    # A stub sleep so the retry arm costs nothing.
    _stub(bin_dir / "sleep", "#!/bin/sh\nexit 0\n")
    # The full environment, PATH replaced: stubs first, then the
    # system utilities the script needs (dirname, cp). uv itself
    # never lives in /usr/bin or /bin, so the uv-missing arm stays
    # forced. Windows needs the rest of the environment for process
    # creation, so only PATH and HOME are overridden.
    env = {
        **os.environ,
        "PATH": f"{bin_dir}{os.pathsep}/usr/bin{os.pathsep}/bin",
        "HOME": str(home),
    }
    return root, bin_dir, env


def _stub(path: Path, body: str) -> None:
    path.write_text(body)
    path.chmod(path.stat().st_mode | stat.S_IXUSR)


@pytest.mark.skipif(BASH is None, reason="no bash on this machine")
def test_a_failed_uv_install_names_the_network(tmp_path: Path) -> None:
    root, bin_dir, env = _script_home(tmp_path)
    # No uv anywhere, and the installer unreachable.
    _stub(bin_dir / "curl", "#!/bin/sh\nexit 7\n")
    _stub(bin_dir / "sh", f"#!{BASH}\nexit 7\n")
    done = subprocess.run(
        [str(BASH), "setup.sh"], cwd=root, env=env, capture_output=True, text=True
    )
    assert done.returncode == 1
    assert "could not install uv" in done.stderr
    assert "astral.sh" in done.stderr


@pytest.mark.skipif(BASH is None, reason="no bash on this machine")
def test_a_failed_sync_is_named_after_one_retry(tmp_path: Path) -> None:
    root, bin_dir, env = _script_home(tmp_path)
    calls = tmp_path / "uv-calls"
    _stub(
        bin_dir / "uv",
        f'#!/bin/sh\necho "$@" >> "{calls}"\nexit 1\n',
    )
    done = subprocess.run(
        [str(BASH), "setup.sh"], cwd=root, env=env, capture_output=True, text=True
    )
    assert done.returncode == 1
    assert "uv sync failed" in done.stderr
    # The retry arm ran: two sync attempts, not one.
    synced = [line for line in calls.read_text().splitlines() if "sync" in line]
    assert len(synced) == 2


@pytest.mark.skipif(BASH is None, reason="no bash on this machine")
def test_the_happy_path_syncs_locked_records_and_emits(tmp_path: Path) -> None:
    root, bin_dir, env = _script_home(tmp_path)
    calls = tmp_path / "uv-calls"
    _stub(
        bin_dir / "uv",
        f'#!/bin/sh\necho "$@" >> "{calls}"\nmkdir -p "{root}/.venv"\nexit 0\n',
    )
    done = subprocess.run(
        [str(BASH), "setup.sh", "github"],
        cwd=root,
        env=env,
        capture_output=True,
        text=True,
    )
    assert done.returncode == 0, done.stderr
    lines = calls.read_text().splitlines()
    assert any("sync" in line and "--locked" in line for line in lines)
    assert any("env.emit --github" in line and "--no-sync" in line for line in lines)
    receipt = root / ".venv" / ".workshop-sync-receipt"
    assert receipt.read_bytes() == (root / "uv.lock").read_bytes()


# --- the reconcile, fallbacks first -----------------------------------------


def _venv_site(root: Path, *dists: str) -> Path:
    site = root / ".venv" / "lib" / "python3.12" / "site-packages"
    site.mkdir(parents=True, exist_ok=True)
    for previous in site.glob("*.dist-info"):
        shutil.rmtree(previous)
    for dist in dists:
        (site / f"{dist}.dist-info").mkdir()
    return site


def test_cold_states_are_inert(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    import toolroom

    from livery.workshop._reconcile import reconcile

    def _explode(*args: object, **kwargs: object) -> object:
        raise AssertionError("uv must not run on a cold state")

    monkeypatch.setattr(toolroom, "uv", SimpleNamespace(opts=_explode))
    # No lock: footman's uv handoff owns it.
    assert reconcile(tmp_path).ran is False
    # A lock without a venv: same.
    (tmp_path / "uv.lock").write_text(LOCK)
    assert reconcile(tmp_path).ran is False


def test_a_failed_sync_reports_and_never_breaks_the_command(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    import toolroom

    from livery.workshop import _reconcile

    (tmp_path / "uv.lock").write_text(LOCK)
    _venv_site(tmp_path, "something-1.0.0")

    def _opts(**kwargs: object) -> object:
        return lambda *args: SimpleNamespace(code=2, stdout="", stderr="index down\n")

    monkeypatch.setattr(toolroom, "uv", SimpleNamespace(opts=_opts))
    result = _reconcile.reconcile(tmp_path)
    assert result.drifted and not result.synced
    # The failure is uv's own words, and the receipt stays absent so
    # the next command tries again.
    assert "index down" in result.failure
    assert not _reconcile.receipt_path(tmp_path).is_file()
    # apply() reports and returns; it never re-runs on a failure.
    ran: list[object] = []
    monkeypatch.setattr(_reconcile, "_reexec", lambda root: ran.append(root))
    _reconcile.apply(tmp_path)
    assert ran == []


def test_a_current_receipt_is_a_no_op(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    import toolroom

    from livery.workshop._reconcile import receipt_path, reconcile

    (tmp_path / "uv.lock").write_text(LOCK)
    _venv_site(tmp_path, "something-1.0.0")
    receipt_path(tmp_path).write_bytes((tmp_path / "uv.lock").read_bytes())

    def _explode(*args: object, **kwargs: object) -> object:
        raise AssertionError("uv must not run when the receipt is current")

    monkeypatch.setattr(toolroom, "uv", SimpleNamespace(opts=_explode))
    result = reconcile(tmp_path)
    assert result.ran and not result.drifted


def test_drift_syncs_records_and_names_the_changed_code(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    import toolroom

    from livery.workshop import _reconcile

    (tmp_path / "uv.lock").write_text(LOCK)
    _venv_site(tmp_path, "something-1.0.0")
    receipt = _reconcile.receipt_path(tmp_path)
    receipt.write_bytes(b"an older lock")

    def _opts(**kwargs: object) -> object:
        def _sync(*args: str) -> object:
            assert args == ("sync", "--frozen")
            _venv_site(tmp_path, "something-2.0.0")
            return SimpleNamespace(code=0, stdout="", stderr="")

        return _sync

    monkeypatch.setattr(toolroom, "uv", SimpleNamespace(opts=_opts))
    result = _reconcile.reconcile(tmp_path)
    assert result.drifted and result.synced
    assert receipt.read_bytes() == (tmp_path / "uv.lock").read_bytes()
    assert result.changed == ("something-1.0.0.dist-info", "something-2.0.0.dist-info")
    # apply() re-runs exactly when installed code changed.
    monkeypatch.setattr(_reconcile, "reconcile", lambda root: result)
    ran: list[object] = []
    monkeypatch.setattr(_reconcile, "_reexec", lambda root: ran.append(root))
    _reconcile.apply(tmp_path)
    assert ran == [tmp_path]


def test_an_unchanged_sync_does_not_rerun(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    from livery.workshop import _reconcile

    result = _reconcile.Reconciled(ran=True, drifted=True, synced=True, changed=())
    monkeypatch.setattr(_reconcile, "reconcile", lambda root: result)
    monkeypatch.setattr(
        _reconcile, "_reexec", lambda root: pytest.fail("re-ran on unchanged code")
    )
    _reconcile.apply(tmp_path)


def test_the_rerun_guard_refuses_a_second_lap(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch, capsys: pytest.CaptureFixture[str]
) -> None:
    from livery.workshop import _reconcile

    monkeypatch.setenv("WORKSHOP_RECONCILE_REEXEC", "1")
    monkeypatch.setattr(os, "execv", lambda *a: pytest.fail("execv despite the guard"))
    _reconcile._reexec(tmp_path)
    assert "changed again" in capsys.readouterr().err


def test_a_missing_uv_degrades_the_rerun_to_a_note(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch, capsys: pytest.CaptureFixture[str]
) -> None:
    from livery.workshop import _reconcile

    monkeypatch.delenv("WORKSHOP_RECONCILE_REEXEC", raising=False)
    monkeypatch.setattr(shutil, "which", lambda name: None)
    monkeypatch.setattr(
        os, "execv", lambda *a: pytest.fail("execv without a uv to run")
    )
    _reconcile._reexec(tmp_path)
    assert "continuing on the loaded code" in capsys.readouterr().err


def test_the_rerun_goes_through_uv_with_the_original_arguments(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    from livery.workshop import _reconcile

    monkeypatch.delenv("WORKSHOP_RECONCILE_REEXEC", raising=False)
    monkeypatch.setattr(shutil, "which", lambda name: "/stub/uv")
    monkeypatch.setattr(sys, "argv", ["/somewhere/.venv/bin/fm", "check", "--affected"])
    seen: list[tuple[str, list[str]]] = []
    monkeypatch.setattr(os, "execv", lambda path, argv: seen.append((path, list(argv))))
    if sys.platform == "win32":
        pytest.skip("posix exec shape; the windows arm waits and forwards")
    _reconcile._reexec(tmp_path)
    ((path, argv),) = seen
    assert path == "/stub/uv"
    assert argv[:5] == ["/stub/uv", "run", "--project", str(tmp_path), "--no-sync"]
    assert argv[-2:] == ["check", "--affected"]
    assert os.environ.get("WORKSHOP_RECONCILE_REEXEC") == "1"
    os.environ.pop("WORKSHOP_RECONCILE_REEXEC", None)


def test_only_the_runner_process_reconciles(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    from livery.workshop._reconcile import is_cli_process

    # pytest, the refresh child, and an empty argv all stay inert.
    monkeypatch.setattr(sys, "argv", ["/usr/bin/pytest"])
    assert is_cli_process() is False
    monkeypatch.setattr(sys, "argv", ["-c"])
    assert is_cli_process() is False
    monkeypatch.setattr(sys, "argv", [])
    assert is_cli_process() is False
    monkeypatch.setattr(sys, "argv", ["/somewhere/.venv/bin/fm", "check"])
    assert is_cli_process() is True


def test_record_receipt_is_silent_without_a_venv(tmp_path: Path) -> None:
    from livery.workshop._reconcile import receipt_path, record_receipt

    (tmp_path / "uv.lock").write_text(LOCK)
    record_receipt(tmp_path)  # no venv: nothing to record, no raise
    assert not receipt_path(tmp_path).is_file()
    (tmp_path / ".venv").mkdir()
    record_receipt(tmp_path)
    assert receipt_path(tmp_path).read_bytes() == (tmp_path / "uv.lock").read_bytes()


# --- the emission's venv path, per platform ---------------------------------


def test_the_emission_names_the_platform_bin_dir(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    from livery.workshop._env_tasks import venv_bin

    monkeypatch.setattr(sys, "platform", "win32")
    assert venv_bin(tmp_path).name == "Scripts"
    monkeypatch.setattr(sys, "platform", "darwin")
    assert venv_bin(tmp_path).name == "bin"
