"""The store's package contract: its surface and its version."""

from __future__ import annotations

from importlib.metadata import version

import livery.toolroom.store as package


def test_the_version_is_the_installed_distributions() -> None:
    assert package.__version__ == version("livery-toolroom-store")


def test_the_public_surface_is_pinned() -> None:
    assert set(package.__all__) == {
        "ARCHES",
        "ARCHIVE_SUFFIXES",
        "FORMATS",
        "artifact_format",
        "DOWNLOAD_KINDS",
        "HOSTS",
        "KINDS",
        "RUNTIMES",
        "LAYOUT_KEYS",
        "OPTION_KEYS",
        "PACKAGE_VAR",
        "VERSION_VAR",
        "PLATFORMS",
        "POINTER",
        "SURFACE_PLATFORMS",
        "RECORD_SUFFIX",
        "VERB_KEYS",
        "LINKS",
        "LOCK_FILE",
        "MODES",
        "TOOLS",
        "URLS",
        "Artifact",
        "Catalogue",
        "CatalogueError",
        "Delta",
        "Deployment",
        "Ensured",
        "Event",
        "Fetched",
        "FetchError",
        "UnpackError",
        "api_headers",
        "fetch_bytes",
        "fetch_file",
        "fetch_json",
        "unpack",
        "Home",
        "Layout",
        "Listed",
        "Lock",
        "NameCollision",
        "Option",
        "LockError",
        "Locked",
        "Observation",
        "Progress",
        "Record",
        "RecordDelta",
        "RecordError",
        "Requirement",
        "Store",
        "ToolSpec",
        "Verb",
        "StoreError",
        "Surface",
        "__version__",
        "default_mode",
        "export_schema",
        "BUILD_FILE",
        "build_current",
        "class_name",
        "host_key",
        "observations",
        "read_pointer",
        "records_in",
        "render",
        "render_observation",
        "resolve",
        "resolve_lock",
        "schema",
        "npm_cli",
        "silent",
        "spec_from",
        "surface_at",
        "tree_fingerprint",
        "validate",
        "version_key",
    }
