# Generated by the workshop from workshop.toml; the gate keeps
# it matching. Edit the contract (or the emitters) and run
# `fm template.apply`; an edit here is drift.
# The entry contract: uv at the lock's pin -> the venv synced against
# the lock, its native members left for later -> the tools installed
# and the stubs written -> the environment entered here -> the native
# members built against it. Source it to enter this shell; `setup.sh
# github` persists the emission (GITHUB_ENV/GITHUB_PATH) for the CI
# steps after it, which then call fm bare.
_root="$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")" && pwd)"
if ! command -v uv >/dev/null 2>&1; then
    curl -LsSf https://astral.sh/uv/0.12.7/install.sh | sh >&2
    PATH="$HOME/.local/bin:$PATH"
    export PATH
    # Name the install that failed here. Left to fall through, uv's
    # absence surfaces below as "uv sync failed", which sends the
    # reader after the venv instead of after the network.
    if ! command -v uv >/dev/null 2>&1; then
        echo "setup: could not install uv - check network access to astral.sh" >&2
        return 1 2>/dev/null || exit 1
    fi
fi
# On a GitHub job uv's cache and the runner's data directory, the tool
# store under it, live under the runner's temp, the working drive. On
# a Windows runner the working drive is not the home directory's: a
# store on the home drive cannot hardlink its entry points into the
# checkout and copies instead, and so would uv's cache into the venv.
# The workflow restores the store before this script runs and saves
# it after the job; uv's cache is placed for the drive alone. Exported
# before the sync and the materialise, and persisted by the emission
# below for every later step.
if [ "${1:-}" = github ] && [ -n "${RUNNER_TEMP:-}" ]; then
    UV_CACHE_DIR="$RUNNER_TEMP/uv-cache"
    FOOTMAN_DATA_DIR="$RUNNER_TEMP/footman"
    export UV_CACHE_DIR FOOTMAN_DATA_DIR
fi
# An ARRAY, not a string: CI may invoke this with zsh, which does not
# word-split unquoted expansions, so a two-word string would arrive
# as one argument. Arrays expand the same under bash and zsh.
_sync_args=()
[ -f "$_root/uv.lock" ] && _sync_args+=(--locked)
# A native member builds its extension at install against the tools
# the store supplies below (the compiler's helpers, the conan
# provider), so the first sync leaves it out and the second, after
# the environment is entered here, builds it.
_native=()
_sync() { uv sync --project "$_root" "${_sync_args[@]}" "$@" >&2; }
_sync "${_native[@]}" \
    || { sleep 10; _sync "${_native[@]}"; } \
    || { echo "setup: uv sync failed" >&2; return 1 2>/dev/null || exit 1; }
# The sync receipt: the lock as this venv last saw it. The runner's
# per-command reconcile compares the two and re-syncs on drift.
[ -f "$_root/uv.lock" ] && cp "$_root/uv.lock" "$_root/.venv/.workshop-sync-receipt"
_run() { uv run --project "$_root" --no-sync fm "$@"; }
# The tools the lock holds, installed exactly as it holds them and
# never re-resolved here, with a receipt each, and the stubs the type
# checkers read rendered into typings/. The emission below puts the
# receipts' paths on PATH, so a
# tool the venv does not carry (an archive from its own release)
# resolves for the gate. Not fatal: a tool the store could not supply
# is named, and the gate says which check that cost.
_run tools.sync --frozen >&2 \
    || echo "setup: the tools were not materialised; the gate names what is missing" >&2
# Entered here, whether sourced or run: the native members build in
# this shell, and a sourcing shell keeps it.
eval "$(_run env.emit posix)"
if [ ${#_native[@]} -gt 0 ]; then
    _sync || { sleep 10; _sync; } \
        || { echo "setup: a native member did not build against the tools" >&2; \
             return 1 2>/dev/null || exit 1; }
fi
if [ "${1:-}" = github ]; then _run env.emit --github >/dev/null; fi
