"""Contract 18's guard: the core renders no identity but the answers'.

A foreign brand's workspace is born from the base's project seeds in a
scratch directory. Nothing in the rendered or generated bytes may spell
livery except the base extension's own distribution and import names,
which arrive through the contract, never the template. The full
drive (lock, sync, and the stranger's own gate) needs the network,
which the merge path never waits on, so it arms by environment
variable and runs in the scheduled lane.
"""

from __future__ import annotations

import os
import subprocess
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[1]

#: The base extension's own names: the livery spellings an instance
#: legitimately carries, and only through its contract's extension list,
#: the dev group derived from it, and the runner import the seeded
#: tasks.py opens with (livery.footman is the runner's real module;
#: the runner and the tool handles the dev group names by their
#: livery distribution names).
ALLOWED = (
    "livery.workshop",
    "livery-workshop",
    "livery.forge",
    "livery-forge",
    "livery.footman",
    "livery-footman",
    "livery.toolroom.tools",
    "livery-toolroom",
)

_CONTRACT = (
    "[workspace]\n"
    'name = "acme-tools"\n'
    'description = "The acme-tools monorepo (virtual root)."\n'
    'namespace = "acme"\n'
    'authors = [{ name = "Acme", email = "dev@acme.example" }]\n'
    'copyright-year = "2026"\n'
    "extensions = []\n"
    "\n"
    "[forge]\n"
    'kind = "gitea"\n'
    'owner = "acme"\n'
    'url = "https://forge.acme.example"\n'
    "\n"
    "[ci]\n"
    'runners = ["ubuntu-latest"]\n'
    'required-context = "gate"\n'
)


#: Our distributions from this checkout, editable as the workshop's own
#: sources declare them, so uv sees one URL for each.
_LOCAL_SOURCES = "".join(
    f'livery-{name} = {{ path = "{ROOT / "packages" / name}", editable = true }}\n'
    for name in ("workshop", "forge", "toolroom", "footman")
)


def _stranger(destination: Path) -> Path:
    """A foreign brand's workspace: contract written, seeds written, files generated."""
    from livery.workshop._identity import project_facts
    from livery.workshop._seeds import PROJECT, create
    from livery.workshop._templates import apply_generated, package_injections

    destination.mkdir(parents=True, exist_ok=True)
    (destination / "workshop.toml").write_text(_CONTRACT)
    data = {**project_facts(destination), **package_injections(destination)}
    create(destination, destination, (PROJECT,), data)
    apply_generated(destination)
    from livery.workshop._shipped_files import deliver

    deliver(destination)
    return destination


def test_the_render_carries_no_identity_but_the_answers(tmp_path: Path) -> None:
    root = _stranger(tmp_path / "acme-tools")
    offenders = []
    for path in sorted(root.rglob("*")):
        if not path.is_file() or path.suffix == ".png" or "__pycache__" in path.parts:
            # The card seed is a raster; identity lives in text.
            continue
        text = path.read_text(encoding="utf-8")
        # _src_path is a machine-managed receipt: it records where
        # THIS render came from (here, a path on the developer's own
        # machine), never a template byte.
        text = "\n".join(
            line for line in text.splitlines() if not line.startswith("_src_path:")
        )
        for allowed in ALLOWED:
            text = text.replace(allowed, "")
        for brand in ("livery", "willem", "kokke"):
            if brand in text.lower():
                offenders.append(f"{path.relative_to(root)}: spells {brand!r}")
    assert offenders == []
    # The stack arrives through the project's dependencies, so the
    # rendered tasks file mounts nothing.
    assert "plugin(" not in (root / "tasks.py").read_text()
    assert "acme" in (root / "pyproject.toml").read_text()


def _drive_guard() -> None:
    if not os.environ.get("WORKSHOP_CONFORMANCE_DRIVE"):
        pytest.skip(
            "set WORKSHOP_CONFORMANCE_DRIVE=1 to run the full drive:"
            " it locks and syncs a scratch venv over the network"
        )


def _driven_root(tmp_path: Path) -> tuple[Path, dict[str, str]]:
    """A stranger workspace, sourced locally, locked, synced, fm-synced."""
    origin = tmp_path / "origin.git"
    origin.mkdir()
    subprocess.run(
        ["git", "init", "--bare", "-q", "--initial-branch=main"],
        cwd=origin,
        check=True,
    )
    subprocess.run(
        ["git", "clone", "-q", str(origin), "acme-tools"], cwd=tmp_path, check=True
    )
    root = _stranger(tmp_path / "acme-tools")
    subprocess.run(
        ["git", "config", "user.email", "d@acme.example"], cwd=root, check=True
    )
    subprocess.run(["git", "config", "user.name", "Acme"], cwd=root, check=True)
    subprocess.run(["git", "config", "commit.gpgsign", "false"], cwd=root, check=True)
    pyproject = root / "pyproject.toml"
    text = pyproject.read_text()
    text = text.replace(
        "[tool.uv.sources]\n",
        "[tool.uv.sources]\n" + _LOCAL_SOURCES,
        1,
    )
    pyproject.write_text(text)
    subprocess.run(["git", "add", "-A"], cwd=root, check=True)
    subprocess.run(["git", "commit", "-qm", "chore: birth"], cwd=root, check=True)
    subprocess.run(["git", "push", "-q", "-u", "origin", "main"], cwd=root, check=True)
    # A drive-local uv cache: the shared cache keys a path
    # dependency's built wheel on its pyproject alone, so a stale
    # build from an earlier drive would resurface on every sync the
    # verbs run mid-test. Cold once per drive, correct throughout.
    env = {
        **os.environ,
        "VIRTUAL_ENV": "",
        "UV_CACHE_DIR": str(tmp_path / "uv-cache"),
        # The drive is a stranger's machine: the operator's own
        # shared env (tokens, rig addresses) must not leak in
        # through the runner-config cascade.
        "XDG_CONFIG_HOME": str(tmp_path / "xdg"),
    }
    for step in (
        ["uv", "lock"],
        [
            "uv",
            "sync",
            "--reinstall-package",
            "livery-workshop",
            "--reinstall-package",
            "livery-forge",
        ],
        ["uv", "run", "fm", "sync"],
    ):
        done = subprocess.run(step, cwd=root, env=env, capture_output=True, text=True)
        assert done.returncode == 0, (
            f"{' '.join(step)} exited {done.returncode}:\n{done.stdout}\n{done.stderr}"
        )
    return root, env


def test_the_stranger_drives_the_whole_loop(tmp_path: Path) -> None:
    _drive_guard()
    origin = tmp_path / "origin.git"
    origin.mkdir()
    subprocess.run(
        ["git", "init", "--bare", "-q", "--initial-branch=main"],
        cwd=origin,
        check=True,
    )
    subprocess.run(
        ["git", "clone", "-q", str(origin), "acme-tools"], cwd=tmp_path, check=True
    )
    root = _stranger(tmp_path / "acme-tools")
    subprocess.run(
        ["git", "config", "user.email", "d@acme.example"], cwd=root, check=True
    )
    subprocess.run(["git", "config", "user.name", "Acme"], cwd=root, check=True)
    # The local checkout stands in for the published wheels: the
    # stranger's dev group names the extension distributions, and this
    # suite must prove the loop without an index.
    pyproject = root / "pyproject.toml"
    text = pyproject.read_text()
    text = text.replace(
        "[tool.uv.sources]\n",
        "[tool.uv.sources]\n" + _LOCAL_SOURCES,
        1,
    )
    pyproject.write_text(text)
    subprocess.run(["git", "add", "-A"], cwd=root, check=True)
    subprocess.run(["git", "commit", "-qm", "chore: birth"], cwd=root, check=True)
    subprocess.run(["git", "push", "-q", "-u", "origin", "main"], cwd=root, check=True)

    env = {**os.environ, "VIRTUAL_ENV": ""}
    # uv judges a path dependency fresh by its pyproject alone, so the
    # local stand-ins are rebuilt explicitly or an edited source would
    # test yesterday's wheel.
    for step in (
        ["uv", "lock"],
        [
            "uv",
            "sync",
            "--reinstall-package",
            "livery-workshop",
            "--reinstall-package",
            "livery-forge",
        ],
        ["uv", "run", "fm", "sync"],
        ["uv", "run", "fm", "template.check"],
        ["uv", "run", "fm", "check"],
    ):
        done = subprocess.run(step, cwd=root, env=env, capture_output=True, text=True)
        assert done.returncode == 0, (
            f"{' '.join(step)} exited {done.returncode}:\n{done.stdout}\n{done.stderr}"
        )
    # Second sync run: idempotent and quiet on the content channels.
    again = subprocess.run(
        ["uv", "run", "fm", "sync"], cwd=root, env=env, capture_output=True, text=True
    )
    assert again.returncode == 0


def test_the_rehearsal_runs_a_graph_of_both_kinds(tmp_path: Path) -> None:
    """The armed release rehearsal over a native library and an extension.

    Both kinds are wired through the real verbs, the gate runs with
    the honest skips, and `fm workflow.release --local` derives,
    stamps, builds (conan create for the library, cibuildwheel for
    the extension), validates, and rolls the tree back.
    """
    _drive_guard()
    for tool in ("conan", "cmake", "ninja", "cc"):
        import shutil as _shutil

        if _shutil.which(tool) is None:
            pytest.skip(f"{tool} must resolve for the native rehearsal")
    root, env = _driven_root(tmp_path)
    # No forge token reaches the rehearsal: the stranger's forge is
    # fictional, and a real token in the caller's shell would make
    # git-cliff attempt the author lookup instead of its offline arm.
    for variable in ("FORGE_TOKEN", "GITEA_TOKEN", "GITHUB_TOKEN", "GITLAB_TOKEN"):
        env.pop(variable, None)
    for name, kind in (
        ("geometry", "package-cpp-conan"),
        ("ext", "package-python-nanobind"),
    ):
        made = subprocess.run(
            ["uv", "run", "fm", "new.package", name, f"--kind={kind}"],
            cwd=root,
            env=env,
            capture_output=True,
            text=True,
        )
        assert made.returncode == 0, f"{made.stdout}\n{made.stderr}"
    subprocess.run(["git", "add", "-A"], cwd=root, check=True)
    subprocess.run(
        ["git", "commit", "-qm", "feat: the native library and the extension"],
        cwd=root,
        check=True,
    )
    gate = subprocess.run(
        ["uv", "run", "fm", "check"], cwd=root, env=env, capture_output=True, text=True
    )
    assert gate.returncode == 0, f"{gate.stdout}\n{gate.stderr}"
    assert "packages/geometry (cpp-conan): configure, build, ctest run" in gate.stdout
    rehearsed = subprocess.run(
        ["uv", "run", "fm", "workflow.release", "geometry", "ext", "--local"],
        cwd=root,
        env=env,
        capture_output=True,
        text=True,
    )
    assert rehearsed.returncode == 0, f"{rehearsed.stdout}\n{rehearsed.stderr}"
    # The newborn's first release is v0.0.0, the baseline receipt
    # (ruled 2026-09-05, hse's own practice); feature counting
    # starts after it.
    assert "would release: acme-geometry v0.0.0, acme-ext v0.0.0" in rehearsed.stdout
    assert "isolated legs skip" in rehearsed.stdout
    clean = subprocess.run(
        ["git", "status", "--porcelain"], cwd=root, capture_output=True, text=True
    )
    assert clean.stdout.strip() == "", clean.stdout
