"""This repository's namespace roots: each holds its public names in one api module.

Our convention, not the workshop's: every distribution root is a PEP 420
namespace with no __init__.py, its public names live in <root>.api,
and api and testing are names no module takes anywhere but
directly under a root. The api holds what an __init__.py would hold: a
public package under a root keeps its own path, and the api declares it,
imported for the checkers and listed in __all__. A root with no public
names, an extension's, has no api either.
"""

from __future__ import annotations

import importlib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

#: Each root's public names when its __init__.py held them: the move to
#: api changes where they live and nothing else. livery.toolroom.tools
#: has no __all__, so its public module names stand in.
EXPORTS: dict[str, list[str]] = {
    "livery.footman": [
        "App",
        "Arg",
        "Argv",
        "AuditEntry",
        "Brand",
        "Context",
        "Exists",
        "Failed",
        "FetchError",
        "Forward",
        "GlobalOption",
        "Group",
        "Hidden",
        "Invocation",
        "IsDir",
        "IsFile",
        "Lane",
        "Many",
        "NoSplit",
        "Result",
        "ResultView",
        "RunFailed",
        "Runner",
        "Secret",
        "Section",
        "Stdin",
        "Stdout",
        "Stream",
        "TaskView",
        "Tasks",
        "TimedOut",
        "__version__",
        "ask",
        "attended",
        "between",
        "cache_dir",
        "capture",
        "chdir",
        "check",
        "colored",
        "config_dir",
        "config_file",
        "config_section",
        "confirm",
        "console_lane",
        "cwd",
        "cwd_lane",
        "data_dir",
        "default",
        "dist",
        "doc",
        "docstrings",
        "env",
        "exists",
        "expose",
        "fail",
        "fetch",
        "forward",
        "given",
        "group",
        "handing_off",
        "hidden",
        "include",
        "inherited",
        "installed_entry_points",
        "isdir",
        "isfile",
        "lane",
        "main",
        "mark",
        "markdown",
        "matching",
        "nosplit",
        "parallel",
        "passthrough",
        "plugin",
        "post_task",
        "post_tasks",
        "pre_bind",
        "pre_record",
        "pre_reexec",
        "pre_task",
        "pre_tasks",
        "prog",
        "progress",
        "project_root",
        "prompt",
        "recording",
        "requires",
        "requires_dep",
        "requires_env",
        "requires_tool",
        "rescan_entry_points",
        "run",
        "section",
        "select",
        "stdin",
        "stdout",
        "step",
        "stream",
        "suggest",
        "task",
        "track",
        "tty",
        "use_context",
        "user_tasks_file",
        "wrap_bind",
        "wrap_task",
    ],
    "livery.forge": [
        "Asset",
        "Capability",
        "CheckState",
        "Checks",
        "Codeowners",
        "CodeownersEntry",
        "CombinedStatus",
        "Comment",
        "Conclusion",
        "Forge",
        "ForgeError",
        "GiteaForge",
        "GithubForge",
        "GitlabForge",
        "Issue",
        "Issues",
        "Job",
        "Label",
        "MergeCategory",
        "MergeState",
        "Protection",
        "PullRequest",
        "PullRequests",
        "RateBudget",
        "RateLimited",
        "Registry",
        "RegistryKind",
        "Release",
        "Releases",
        "RepoConfig",
        "RepoInfo",
        "Repository",
        "Review",
        "ReviewState",
        "Run",
        "RunStatus",
        "Schedule",
        "ScheduleEvent",
        "ScheduleEventKind",
        "Schedules",
        "SimpleRegistry",
        "StateFilter",
        "Step",
        "Unsupported",
        "__version__",
        "classify_gitea_merge_refusal",
        "classify_github_mergeable_state",
        "classify_gitlab_detailed_status",
        "classify_merge_refusal",
        "gitea_configured_host",
        "gitea_is_configured_host",
        "gitlab_configured_host",
        "gitlab_is_configured_host",
        "merge_state",
    ],
    "livery.strongroom": [
        "ALGORITHMS",
        "Algorithm",
        "Clock",
        "Digest",
        "DropReport",
        "ENTRY_RUNGS",
        "Entry",
        "EntryKind",
        "EntryRung",
        "ErasedObject",
        "FillPolicy",
        "FolderSource",
        "FormatError",
        "Group",
        "GroupHalfApplied",
        "HashConstructor",
        "Hasher",
        "HttpSource",
        "IntegrityError",
        "LAYOUT_VERSION",
        "Landed",
        "Link",
        "LockTimeout",
        "MANIFEST_NAME",
        "MUTATION_CLASSES",
        "MadeRung",
        "Manifest",
        "ManifestError",
        "MissingObject",
        "Move",
        "MutationClass",
        "NAME_BUDGET",
        "Namespace",
        "NoSuchPending",
        "NotAGroup",
        "NotFastForward",
        "OWNED",
        "ObjectState",
        "OriginHint",
        "PATH_BUDGET",
        "PENDING",
        "PINS",
        "Pending",
        "Progress",
        "RUNGS",
        "RefConflict",
        "RefProtected",
        "RefRecord",
        "RefTampered",
        "Rung",
        "RungUnavailable",
        "SHA256",
        "ScrubReport",
        "ShedReport",
        "Source",
        "Store",
        "StoreError",
        "Subject",
        "SubjectKind",
        "SweepReport",
        "Tombstone",
        "Transaction",
        "Tree",
        "UnknownNamespace",
        "Unreachable",
        "Value",
        "Version",
        "ViewEntry",
        "ViewRecord",
        "WriteOnceRefused",
        "__version__",
        "canonical",
        "cbor",
        "check_name",
        "check_target",
        "check_timestamp",
        "digest_of",
        "digest_stream",
        "fetch_url",
        "now",
        "silent",
    ],
    "livery.toolroom.bench": ["Refreshed", "__version__", "submit_refresh", "tasks"],
    "livery.toolroom.store": [
        "ARCHES",
        "ARCHIVE_SUFFIXES",
        "Artifact",
        "BUILD_FILE",
        "Catalogue",
        "CatalogueError",
        "DOWNLOAD_KINDS",
        "Delta",
        "Deployment",
        "Ensured",
        "Event",
        "FORMATS",
        "FetchError",
        "Fetched",
        "GRAPHS",
        "Graph",
        "HOSTS",
        "Home",
        "KINDS",
        "LAYOUT_KEYS",
        "LINKS",
        "LOCK_FILE",
        "Layout",
        "Listed",
        "Lock",
        "LockError",
        "Locked",
        "MODES",
        "NameCollision",
        "OPTION_KEYS",
        "Observation",
        "Option",
        "PACKAGE_VAR",
        "PLATFORMS",
        "POINTER",
        "Progress",
        "RECORD_SUFFIX",
        "RUNTIMES",
        "Record",
        "RecordDelta",
        "RecordError",
        "Requirement",
        "SURFACE_PLATFORMS",
        "Scope",
        "Spec",
        "SpecError",
        "Store",
        "StoreError",
        "Surface",
        "TOOLS",
        "ToolSpec",
        "URLS",
        "UnpackError",
        "VERB_KEYS",
        "VERSION_VAR",
        "Verb",
        "__version__",
        "api_headers",
        "artifact_format",
        "build_current",
        "bun_global_project",
        "class_name",
        "default_mode",
        "export_schema",
        "fetch_bytes",
        "fetch_file",
        "fetch_json",
        "host_key",
        "npm_cli",
        "observations",
        "read_pointer",
        "records_in",
        "render",
        "render_observation",
        "resolve",
        "resolve_lock",
        "schema",
        "silent",
        "spec_from",
        "surface_at",
        "tree_fingerprint",
        "unpack",
        "validate",
        "version_key",
    ],
    "livery.toolroom.tools": [
        "Any",
        "Argv",
        "ArgvTool",
        "Flag",
        "Iterator",
        "NamedTuple",
        "Result",
        "Sequence",
        "Tool",
        "ToolError",
        "TypeAlias",
        "Value",
        "ValuedFlag",
        "annotations",
        "off",
        "read_version",
        "version_tuple",
    ],
    "livery.workshop": [
        "CheckRecord",
        "Claim",
        "Edge",
        "Fragment",
        "GateContext",
        "Option",
        "PACKAGE",
        "PACKAGES",
        "PATHS",
        "Package",
        "WHOLE",
        "__version__",
        "check_option",
        "compile_commands",
        "discover_packages",
        "extension_names",
        "kind_examples",
        "mount_extensions",
        "public_modules",
        "rewrite_nav_block",
        "run_batched",
        "run_suites",
        "scoped_files",
        "scoped_packages",
        "scoped_paths",
        "verify_workspace",
        "workspace_root",
        "workspace_suite",
    ],
}

#: Where each root lives.
SOURCES = {
    "livery.footman": "packages/footman/src/livery/footman",
    "livery.forge": "packages/forge/src/livery/forge",
    "livery.strongroom": "packages/strongroom/src/livery/strongroom",
    "livery.workshop": "packages/workshop/src/livery/workshop",
    "livery.toolroom.store": "packages/toolroom-store/src/livery/toolroom/store",
    "livery.toolroom.bench": "packages/toolroom-bench/src/livery/toolroom/bench",
    "livery.toolroom.tools": "packages/toolroom/src/livery/toolroom/tools",
}

#: The roots with no public names: a namespace with neither api.py nor
#: __init__.py, reached through an entry point alone.
BARE = {
    "livery.extensions.docs": "packages/workshop/src/livery/extensions/docs",
    "livery.extensions.basedpyright": (
        "packages/extensions/basedpyright/src/livery/extensions/basedpyright"
    ),
    "livery.extensions.ruff": "packages/extensions/ruff/src/livery/extensions/ruff",
}

#: The names a module takes only directly under a root.
RESERVED = ("api", "testing")


def _public(module: object) -> list[str]:
    declared = getattr(module, "__all__", None)
    if declared is not None:
        return sorted(declared)
    # A tool handle is made on first use and kept on the module, so
    # which handles exist depends on what ran before: the module's own
    # names are the surface.
    tool = getattr(module, "Tool", None)
    return sorted(
        name
        for name, value in vars(module).items()
        if not name.startswith("_") and not (tool and isinstance(value, tool))
    )


def test_api_exports_what_the_package_exported() -> None:
    for root, names in EXPORTS.items():
        assert _public(importlib.import_module(f"{root}.api")) == names, root


def test_every_distribution_root_is_a_namespace_with_one_api() -> None:
    problems: list[str] = []
    roots = {ROOT / path for path in SOURCES.values()}
    for directory in roots:
        if (directory / "__init__.py").exists():
            problems.append(f"{directory}: a root carries no __init__.py")
        if not (directory / "api.py").is_file():
            problems.append(f"{directory}: a root holds its names in api.py")
    # A member at either depth: packages/<name>/ or packages/<group>/<name>/.
    for src in sorted([*ROOT.glob("packages/*/src"), *ROOT.glob("packages/*/*/src")]):
        for namespace in (src / "livery", src / "livery" / "extensions"):
            if (namespace / "__init__.py").exists():
                problems.append(f"{namespace}: a namespace carries no __init__.py")
        for path in sorted(src.rglob("*")):
            if "__pycache__" in path.parts or path.stem not in RESERVED:
                continue
            if path.parent not in roots:
                problems.append(f"{path.relative_to(ROOT)}: {path.stem} is reserved")
    assert problems == []


def test_a_root_with_no_public_names_has_neither_api_nor_init() -> None:
    problems = [
        f"{path}: {name} in a root with no public names"
        for path in BARE.values()
        for name in ("api.py", "__init__.py")
        if (ROOT / path / name).exists()
    ]
    assert problems == []
    assert all((ROOT / path).is_dir() for path in BARE.values())
