"""Contract 18's guard: the core renders no identity but the answers'.

A foreign brand renders the ``project`` kind into a scratch
workspace. Nothing in the rendered or generated bytes may spell
livery except the base layer's own distribution and import names,
which arrive through the contract, never the template. The full
drive (lock, sync, and the stranger's own gate) needs the network,
which the merge path never waits on, so it arms by environment
variable and runs in the scheduled lane.
"""

from __future__ import annotations

import os
import subprocess
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[1]

#: The base layer's own names: the one livery spelling an instance
#: legitimately carries, and only through its contract's layer list
#: and the dev group derived from it.
ALLOWED = ("livery.workshop", "livery-workshop", "livery.forge", "livery-forge")

_CONTRACT = (
    "[workspace]\n"
    'layers = ["livery.workshop"]\n'
    "\n"
    "[forge]\n"
    'kind = "gitea"\n'
    'owner = "acme"\n'
    'url = "https://forge.acme.example"\n'
    "\n"
    "[ci]\n"
    'runners = ["ubuntu-latest"]\n'
    'required_context = "gate"\n'
)


def _stranger(destination: Path) -> Path:
    """A foreign brand's workspace: contract seeded, rendered, generated."""
    from livery.workshop._templates import apply_generated, render

    destination.mkdir(parents=True, exist_ok=True)
    (destination / "workshop.toml").write_text(_CONTRACT)
    render(
        ROOT / "templates",
        destination,
        {
            "kind": "project",
            "project_name": "acme-tools",
            "project_description": "The acme-tools monorepo (virtual root).",
            "author_name": "Acme",
            "author_email": "dev@acme.example",
            "copyright_year": "2026",
            "namespace_package": "acme",
            "packages": [],
            "runner_prog": "fm",
            "python_floor": "3.11",
            "layer_imports": ["livery.workshop"],
            "layer_requirements": ["livery-workshop"],
        },
    )
    apply_generated(destination)
    return destination


def test_the_render_carries_no_identity_but_the_answers(tmp_path: Path) -> None:
    root = _stranger(tmp_path / "acme-tools")
    offenders = []
    for path in sorted(root.rglob("*")):
        if not path.is_file():
            continue
        text = path.read_text(encoding="utf-8")
        # _src_path is a machine-managed receipt: it records where
        # THIS render came from (here, a path on the developer's own
        # machine), never a template byte.
        text = "\n".join(
            line for line in text.splitlines() if not line.startswith("_src_path:")
        )
        for allowed in ALLOWED:
            text = text.replace(allowed, "")
        for brand in ("livery", "willem", "kokke"):
            if brand in text.lower():
                offenders.append(f"{path.relative_to(root)}: spells {brand!r}")
    assert offenders == []
    # The stack arrived through the contract, not a template byte.
    assert 'plugin("livery.workshop")' in (root / "tasks.py").read_text()
    assert "acme" in (root / "pyproject.toml").read_text()


def test_the_stranger_drives_the_whole_loop(tmp_path: Path) -> None:
    if not os.environ.get("WORKSHOP_CONFORMANCE_DRIVE"):
        pytest.skip(
            "set WORKSHOP_CONFORMANCE_DRIVE=1 to run the full drive:"
            " it locks and syncs a scratch venv over the network"
        )
    origin = tmp_path / "origin.git"
    origin.mkdir()
    subprocess.run(
        ["git", "init", "--bare", "-q", "--initial-branch=main"],
        cwd=origin,
        check=True,
    )
    subprocess.run(
        ["git", "clone", "-q", str(origin), "acme-tools"], cwd=tmp_path, check=True
    )
    root = _stranger(tmp_path / "acme-tools")
    subprocess.run(
        ["git", "config", "user.email", "d@acme.example"], cwd=root, check=True
    )
    subprocess.run(["git", "config", "user.name", "Acme"], cwd=root, check=True)
    # The local checkout stands in for the published wheels: the
    # stranger's dev group names the layer distributions, and this
    # suite must prove the loop without an index.
    pyproject = root / "pyproject.toml"
    text = pyproject.read_text()
    text = text.replace(
        "[tool.uv.sources]\n",
        "[tool.uv.sources]\n"
        f'livery-workshop = {{ path = "{ROOT / "packages/workshop"}" }}\n'
        f'livery-forge = {{ path = "{ROOT / "packages/forge"}" }}\n',
        1,
    )
    pyproject.write_text(text)
    subprocess.run(["git", "add", "-A"], cwd=root, check=True)
    subprocess.run(["git", "commit", "-qm", "chore: birth"], cwd=root, check=True)
    subprocess.run(["git", "push", "-q", "-u", "origin", "main"], cwd=root, check=True)

    env = {**os.environ, "VIRTUAL_ENV": ""}
    # uv judges a path dependency fresh by its pyproject alone, so the
    # local stand-ins are rebuilt explicitly or an edited source would
    # test yesterday's wheel.
    for step in (
        ["uv", "lock"],
        [
            "uv",
            "sync",
            "--reinstall-package",
            "livery-workshop",
            "--reinstall-package",
            "livery-forge",
        ],
        ["uv", "run", "fm", "sync"],
        ["uv", "run", "fm", "template.check"],
        ["uv", "run", "fm", "check"],
    ):
        done = subprocess.run(step, cwd=root, env=env, capture_output=True, text=True)
        assert done.returncode == 0, (
            f"{' '.join(step)} exited {done.returncode}:\n{done.stdout}\n{done.stderr}"
        )
    # Second sync run: idempotent and quiet on the content channels.
    again = subprocess.run(
        ["uv", "run", "fm", "sync"], cwd=root, env=env, capture_output=True, text=True
    )
    assert again.returncode == 0
