"""Shell completion installers — `fm --install-completion=bash|zsh|fish|pwsh`.

Each generated script calls `<prog> --complete -- WORD...` on TAB: the
stdlib-only hot path that answers from the cached manifest without importing
footman or the user's code. Scripts are generated per brand, so a custom CLI
(`acme --install-completion=zsh`) installs completion for *its* name.

Install layout (all idempotent — running twice changes nothing):

- bash: script in `$XDG_DATA_HOME/<prog>/completion.bash`, one guarded
  `source` line appended to `~/.bashrc`.
- zsh: script in `$XDG_DATA_HOME/<prog>/completion.zsh`, one guarded
  `source` line appended to `~/.zshrc`.
- fish: `~/.config/fish/completions/<prog>.fish` — fish auto-loads the
  directory; no rc editing at all.
- pwsh: script in `$XDG_DATA_HOME/<prog>/completion.ps1`, one guarded
  dot-source line appended to the profile PowerShell itself reports
  (`$PROFILE`); works for PowerShell 7+ and Windows PowerShell 5.
- nushell: script in `$XDG_DATA_HOME/<prog>/completion.nu`, one guarded
  `source` line appended to the config nushell itself reports
  (`$nu.config-path`). The hook *wraps* any existing external completer
  (carapace, fish-based, …) instead of replacing it.
"""

from __future__ import annotations

import contextlib
import os
import shutil
import subprocess
import sys
from pathlib import Path

from livery.footman import _encoding, _paths

SHELLS = ("bash", "zsh", "fish", "pwsh", "nushell")


class InstallError(Exception):
    """Completion could not be installed; the message says why."""


_BASH = """\
# {prog} shell completion (generated by `{prog} --install-completion=bash`)
_{fn}_complete() {{
    # An index loop, not "${{COMP_WORDS[@]:1:COMP_CWORD}}": the quoted array
    # slice collapses to a single word on macOS's bash 3.2.
    local -a words=()
    local i
    for ((i = 1; i <= COMP_CWORD; i++)); do
        words[i - 1]=${{COMP_WORDS[i]}}
    done
    COMPREPLY=()
    # Capture into a variable (not `< <(...)`) so we can read the exit code.
    # `local out` then `out=$(...)` on separate lines — `local out=$(...)`
    # would make $? the exit of `local`, not of the completion call.
    local out ret
    out=$({prog} --complete -- "${{words[@]}}" 2>/dev/null)
    ret=$?
    # Exit 100 = a path value. With no stdout that is "every file": leave
    # COMPREPLY empty and let `-o default` (below) hand off to readline's
    # filename completion — works on bash 3.2. One line of stdout is a
    # `matching()` glob, and readline cannot be told about one, so build the
    # list here instead. Directories come along whatever the pattern says, or
    # a match one level down would be unreachable.
    if (( ret == 100 )); then
        [[ -n $out ]] || return 0
        # A `matching()` glob, and readline cannot be told about one — so
        # build the list here. The head through the last `=` stays put and
        # rides every candidate, exactly as the comma branch below does:
        # whether bash split the word there depends on COMP_WORDBREAKS, and
        # this reading is right either way. Directories come along whatever
        # the pattern says, or a match one level down is unreachable.
        local cur=${{COMP_WORDS[COMP_CWORD]}} glob=${{out%%$'\\n'*}}
        local head="" tail=$cur f
        [[ $cur == *=* ]] && {{ head="${{cur%=*}}="; tail="${{cur##*=}}"; }}
        compopt +o default 2>/dev/null
        while IFS= read -r f; do
            [[ -n $f ]] || continue
            [[ -d $f ]] && f+=/
            printf -v f '%q' "$f"
            COMPREPLY+=("$head$f")
        done < <(compgen -d -- "$tail"; compgen -f -X "!$glob" -- "$tail")
        # A lone directory keeps the cursor in place for its children.
        (( ${{#COMPREPLY[@]}} == 1 )) && [[ ${{COMPREPLY[0]}} == */ ]] && \\
            compopt -o nospace 2>/dev/null
        return 0
    fi
    if (( ret == 101 )); then
        # Exit 101 = a comma-splitting path value mid-list (`--paths=a,b`):
        # readline would match the whole word, comma and all, so complete
        # the segment after the last comma here and re-attach the typed
        # items on every candidate.
        local cur=${{COMP_WORDS[COMP_CWORD]}}
        [[ $cur == *,* ]] || return 0
        compopt +o default 2>/dev/null
        local head="${{cur%,*}}," f
        while IFS= read -r f; do
            [[ -d $f ]] && f+=/
            printf -v f '%q' "$f"
            COMPREPLY+=("$head$f")
        done < <(compgen -f -- "${{cur##*,}}")
        # A lone directory match keeps the cursor in place for its children.
        (( ${{#COMPREPLY[@]}} == 1 )) && [[ ${{COMPREPLY[0]}} == */ ]] && \\
            compopt -o nospace 2>/dev/null
        return 0
    fi
    # Exit 103 = the tasks file failed to import; the reason is on stderr.
    # bash has no way to display a line without offering it for insertion,
    # so stay silent — but switch the filename fallback off first, or the
    # silence fills with files offered as if they were tasks.
    if (( ret == 103 )); then
        compopt +o default 2>/dev/null
        return 0
    fi
    # Not a file: on bash 4+ switch the default filename fallback off so a value
    # with no candidates stays empty. bash 3.2 has no compopt and keeps the
    # blunt fallback — no regression, it already behaved that way.
    compopt +o default 2>/dev/null
    [[ -n $out ]] || return 0
    # Exit 102 = the candidates continue a comma-splitting value: glue the
    # cursor (no trailing space), so the comma — or the closing space — is
    # the next keystroke instead of a deletion. bash 3.2 has no compopt and
    # keeps the space, exactly as before.
    (( ret == 102 )) && compopt -o nospace 2>/dev/null
    # Read one candidate per line and %q-quote each, so a candidate like *.md or
    # "a b" is inserted literally — never pathname-expanded the way a
    # split-and-glob command substitution into the array would. bash has no
    # description column, so drop anything after the first tab.
    local line
    while IFS= read -r line; do
        line=${{line%%$'\\t'*}}
        printf -v line '%q' "$line"
        COMPREPLY+=("$line")
    done <<< "$out"
}}
complete -o default -F _{fn}_complete {prog}
"""

_ZSH = """\
# {prog} shell completion (generated by `{prog} --install-completion=zsh`)
if ! typeset -f compdef >/dev/null 2>&1; then
    # -u: skip compaudit's interactive prompt — this fallback only fires when
    # nothing else initialised completion (fresh HOMEs, non-interactive use),
    # exactly where a prompt would wedge instead of asking.
    autoload -Uz compinit && compinit -u
fi
_{fn}_complete() {{
    local -a items sfx
    local raw line ret
    # (@) + quotes keeps the empty current word when the cursor follows a
    # space — unquoted expansion would drop it.
    raw="$({prog} --complete -- "${{(@)words[2,CURRENT]}}" 2>/dev/null)"
    ret=$?
    # Exit 100 = a path value: defer to zsh's own file completion, which
    # honours the user's file colours and list settings. compset strips an
    # attached `--opt=` prefix first so the value part completes in place.
    # One line of stdout is a `matching()` glob — `_files -g` narrows to it
    # and still offers directories, so a match one level down stays reachable.
    (( ret == 100 )) && {{
        compset -P '*='
        if [[ -n $raw ]]; then _files -g "${{raw%%$'\\n'*}}"; else _files; fi
        return
    }}
    # Exit 101 = a comma-splitting path value mid-list: strip through the
    # last `=` or comma too, so each list item completes as its own path.
    (( ret == 101 )) && {{ compset -P '*[=,]'; _files; return; }}
    # Exit 103 = the tasks file failed to import (stdout stays empty so
    # older hooks show plain silence). One more call with `--why` fetches
    # the reason on stdout — the one channel every shell captures the same
    # way — and `_message` displays it without offering anything to insert.
    (( ret == 103 )) && {{
        local why
        why="$({prog} --complete --why -- "${{(@)words[2,CURRENT]}}" 2>/dev/null)"
        [[ -n $why ]] && _message -r "${{why%%$'\\n'*}}"
        return
    }}
    for line in ${{(f)raw}}; do
        # `value:description` feeds _describe, which right-aligns the
        # descriptions into a column and honours the user's completion colours
        # (list-colors / descriptions format). A tab-less line — an option or a
        # choice value — is a bare value with no description.
        if [[ $line == *$'\\t'* ]]; then
            items+=("${{line%%$'\\t'*}}:${{line#*$'\\t'}}")
        else
            items+=("$line")
        fi
    done
    # Exit 102 = the candidates continue a comma-splitting value: append the
    # comma as an auto-removable suffix (extra compadd options ride through
    # _describe) — accepting `eu` writes `eu,`, and a space or Enter takes
    # the comma back off.
    (( ret == 102 )) && sfx=(-q -S ',')
    (( ${{#items}} )) && _describe -t {fn} '{prog}' items $sfx
}}
compdef _{fn}_complete {prog}
"""

_FISH = """\
# {prog} shell completion (generated by `{prog} --install-completion=fish`)
function __{fn}_complete
    set -l words (commandline -opc) (commandline -ct)
    set -l out ({prog} --complete -- $words[2..-1] 2>/dev/null)
    # `test` overwrites $status, so read the resolver's exit code once.
    set -l ret $status
    # Exit 100 = a path value: hand off to fish's own path completion. An
    # attached `--opt=path` token completes by stripping the prefix for the
    # path walk and re-attaching it on each candidate (fish replaces the
    # whole token).
    if test $ret -eq 100
        set -l tok (commandline -ct)
        set -l pre (string match -r -- '^-[^=]*=' $tok)
        set -l paths
        if test -n "$pre"
            set paths (__fish_complete_path (string replace -- $pre '' $tok))
        else
            set paths (__fish_complete_path $tok)
        end
        # One line of stdout is a `matching()` glob. Keep directories
        # whatever it says — a match one level down has to stay reachable —
        # and otherwise keep only names the pattern matches. Each candidate
        # is `path\\tdescription`, so match on the path half alone.
        if set -q out[1]
            set -l keep
            for cand in $paths
                set -l p (string split -m 1 \\t -- $cand)[1]
                if string match -q -- '*/' $p
                    set -a keep $cand
                else if string match -q -- $out[1] (basename $p)
                    set -a keep $cand
                end
            end
            set paths $keep
        end
        printf '%s\\n' $paths | string replace -r -- '^' "$pre"
    else if test $ret -eq 101
        # Exit 101 = a comma-splitting path value mid-list: the head through
        # the last `=` or comma stays, the tail completes as its own path,
        # and each candidate re-attaches the head.
        set -l tok (commandline -ct)
        set -l pre (string match -r -- '^.*[=,]' $tok)
        if test -n "$pre"
            __fish_complete_path (string replace -- $pre '' $tok) | \\
                string replace -r -- '^' $pre
        else
            __fish_complete_path $tok
        end
    else if test $ret -eq 103
        # A broken tasks file (stdout stays empty so older hooks show plain
        # silence). One more call with `--why` fetches the reason on stdout;
        # fish has no message row, so re-offer the typed word — a no-op
        # insert — carrying the reason as its description; a bare Tab stays
        # silent.
        set -l tok (commandline -ct)
        if test -n "$tok"
            set -l why ({prog} --complete --why -- $words[2..-1] 2>/dev/null)
            if set -q why[1]
                printf '%s\\t%s\\n' $tok $why[1]
            end
        end
    else if test $ret -eq 102; and set -q out[1]
        # Exit 102 = the candidates continue a comma-splitting value: fish
        # inserts a candidate that ends in a comma with no trailing space,
        # so the comma rides each value half and the next element is one
        # Tab away. The description (after the tab) stays untouched.
        printf '%s\\n' $out | string replace -r -- '^([^\\t]*)' '$1,'
    else if set -q out[1]
        printf '%s\n' $out
    end
end
complete -c {prog} -f -a '(__{fn}_complete)'
"""

_PWSH = """\
# {prog} shell completion (generated by `{prog} --install-completion=pwsh`)
Register-ArgumentCompleter -Native -CommandName {prog} -ScriptBlock {{
    param($wordToComplete, $commandAst, $cursorPosition)
    $words = @($commandAst.CommandElements |
        Select-Object -Skip 1 | ForEach-Object {{ $_.ToString() }})
    # WinPS 5.1 and pwsh 7.0-7.2 silently drop an empty-string arg to a native
    # command, so a trailing '' partial can't be passed directly. Flag the empty
    # position instead; the resolver appends the '' itself.
    $empty = if ($wordToComplete -eq '') {{ '--empty-partial' }} else {{ $null }}
    $out = @(& {prog} --complete $empty -- @words 2>$null)
    if ($LASTEXITCODE -eq 100) {{
        # A path value: defer to PowerShell's own filename completion. The
        # head through the last `=` is stripped first and re-attached on each
        # candidate — `CompleteFilename('--env-file=')` looks for a file by
        # that literal name and finds nothing, so an attached `--opt=path`
        # completed to silence here until this was written. Same reading the
        # comma branch below already used.
        $m = [regex]::Match($wordToComplete, '^(.*=)?(.*)$')
        $head = $m.Groups[1].Value
        $files = [System.Management.Automation.CompletionCompleters]::CompleteFilename(
            $m.Groups[2].Value)
        # One line of stdout is a `matching()` glob. Containers come along
        # whatever it says, or a match one level down is unreachable.
        if ($out.Count -gt 0 -and $out[0]) {{
            $glob = $out[0]
            $files = $files | Where-Object {{
                $_.ResultType -eq 'ProviderContainer' -or
                (Split-Path -Leaf $_.CompletionText.Trim("'", '"')) -like $glob
            }}
        }}
        return $files | ForEach-Object {{
            [System.Management.Automation.CompletionResult]::new(
                $head + $_.CompletionText, $head + $_.ListItemText,
                $_.ResultType, $_.ToolTip)
        }}
    }}
    if ($LASTEXITCODE -eq 101) {{
        # A comma-splitting path value mid-list: the head through the last
        # `=` or comma stays; the tail completes as a filename and each
        # result re-attaches the head (completions replace the whole word).
        $m = [regex]::Match($wordToComplete, '^(.*[=,])?([^,]*)$')
        $head = $m.Groups[1].Value
        return [System.Management.Automation.CompletionCompleters]::CompleteFilename(
            $m.Groups[2].Value) | ForEach-Object {{
                [System.Management.Automation.CompletionResult]::new(
                    $head + $_.CompletionText, $head + $_.ListItemText,
                    $_.ResultType, $_.ToolTip)
            }}
    }}
    if ($LASTEXITCODE -eq 103) {{
        # A broken tasks file (stdout stays empty so older hooks show plain
        # silence). One more call with `--why` fetches the reason on stdout
        # — the completion host swallows a native stderr merge outright.
        # Re-offer the typed word — a no-op insert — with the reason as its
        # tooltip; a bare Tab keeps PowerShell's default behaviour (an
        # empty word cannot be a result).
        if ($wordToComplete) {{
            $why = (@(& {prog} --complete --why $empty -- @words 2>$null) `
                -join ' ').Trim()
            if (-not $why) {{ $why = ' ' }}
            return ,[System.Management.Automation.CompletionResult]::new(
                $wordToComplete, $wordToComplete, 'ParameterValue', $why)
        }}
        return
    }}
    if ($out.Count -eq 0 -or -not $out[0]) {{
        # No candidates. Yielding nothing hands the position to PowerShell's
        # default completion — filesystem entries offered as if they were
        # tasks — so re-offer the typed word itself: a visual no-op that
        # keeps the line exactly as it is. An empty word has nothing to
        # re-offer (CompletionResult refuses ''), so the bare-Tab shape
        # keeps PowerShell's default behaviour.
        if ($wordToComplete) {{
            return ,[System.Management.Automation.CompletionResult]::new(
                $wordToComplete, $wordToComplete, 'ParameterValue', ' ')
        }}
        return
    }}
    $out | ForEach-Object {{
        # `value` or `value<tab>description`: the tail becomes the tooltip.
        $parts = $_ -split "`t", 2
        $val = $parts[0]
        $tip = if ($parts.Count -gt 1) {{ $parts[1] }} else {{ $val }}
        [System.Management.Automation.CompletionResult]::new(
            $val, $val, 'ParameterValue', $tip)
    }}
}}
"""

_NU = """\
# {prog} shell completion (generated by `{prog} --install-completion=nushell`)
# Wraps any existing external completer (carapace, …) instead of replacing it.
let __{fn}_prev = ($env.config.completions?.external?.completer? | default null)
$env.config.completions.external.enable = true
$env.config.completions.external.completer = {{|spans|
    if $spans.0 == "{prog}" {{
        let r = (^{prog} --complete -- ...($spans | skip 1) | complete)
        if $r.exit_code == 100 or $r.exit_code == 101 {{
            # A path value: null defers to nushell's built-in file completion.
            # (101 marks a comma-splitting value mid-list; a version-stable
            # comma-aware spelling isn't available, so nushell completes the
            # first list item only.)
            #
            # A `matching()` glob arrives on stdout and is deliberately NOT
            # applied here: filtering would mean returning a list of our own,
            # and that list replaces nushell's file completion outright —
            # losing directory descent, and with it any match below the
            # current directory. An unfiltered walk that reaches every file
            # beats a filtered one that reaches only this directory's.
            null
        }} else if $r.exit_code == 103 {{
            # A broken tasks file (stdout stays empty so older hooks show
            # plain silence). One more call with `--why` fetches the reason
            # on stdout — the record's stderr is not reliably a string on
            # every host, and stdout capture is. Re-offer the typed word —
            # a no-op insert — with the reason in the description column; a
            # bare Tab stays silent.
            # `into binary | decode`: hosts disagree on the captured type
            # (string on some, binary on others) and each coercion alone
            # accepts only one of them; binary-then-decode accepts both.
            let tok = ($spans | last)
            let why = ((^{prog} --complete --why -- ...($spans | skip 1)
                | complete).stdout | into binary | decode utf-8
                | lines | get 0? | default "")
            if $tok != "" and $why != "" {{
                [{{value: $tok, description: $why}}]
            }} else {{
                null
            }}
        }} else {{
            # Split `value<tab>description` into a record so nushell renders the
            # description column; a tab-less line (option/choice) is a bare value.
            $r.stdout | lines | each {{|l|
                let p = ($l | split row (char tab))
                if ($p | length) > 1 {{
                    {{value: $p.0, description: $p.1}}
                }} else {{
                    {{value: $p.0}}
                }}
            }}
        }}
    }} else if $__{fn}_prev != null {{
        do $__{fn}_prev $spans
    }} else {{
        null
    }}
}}
"""

_TEMPLATES = {"bash": _BASH, "zsh": _ZSH, "fish": _FISH, "pwsh": _PWSH, "nushell": _NU}


def script_for(shell: str, prog: str) -> str:
    """The completion script for *shell*, branded for *prog*."""
    fn = prog.replace("-", "_")
    return _TEMPLATES[shell].format(prog=prog, fn=fn)


def _sniff_encoding(raw: bytes) -> tuple[str, str]:
    """(decode, append) encodings for rc bytes, sniffed from any leading BOM.

    The marks come from `_encoding.BOM_ENCODINGS`, the one table the config
    reader also reads. The append encoder is BOM-free (`utf-8`,
    `utf-16-le`/`-be`) so we never inject a second BOM mid-file. With no BOM,
    prefer UTF-8 and fall back to latin-1, which round-trips arbitrary bytes
    rather than raising — an rc file is somebody's shell, not a format with a
    mandatory encoding, so it is read as it lies.
    """
    sniffed = _encoding.sniff_bom(raw)
    if sniffed is not None:
        return sniffed
    try:
        raw.decode("utf-8")
    except UnicodeDecodeError:
        return "latin-1", "latin-1"
    return "utf-8", "utf-8"


def _append_once(rc: Path, line: str) -> bool:
    """Append *line* to *rc* unless present; True if the file changed.

    rc files carry whatever encoding the shell wrote — a Windows PowerShell 5
    `$PROFILE` is UTF-16 with a BOM. Read the bytes, sniff the BOM, and append
    in the matching (BOM-free) encoding, so a UTF-16 profile is neither crashed
    on read nor corrupted by a UTF-8 tail. A residual write failure becomes an
    `InstallError` naming the exact line to add, routed to the existing exit-2
    path instead of a raw traceback.
    """
    try:
        raw = rc.read_bytes() if rc.exists() else b""
    except OSError as exc:
        raise InstallError(_manual_hint(rc, line, exc)) from exc

    read_enc, append_enc = _sniff_encoding(raw)
    existing = raw.decode(read_enc, errors="replace")
    if line in existing:
        return False

    joiner = "" if existing.endswith("\n") or not existing else "\n"
    payload = f"{joiner}{line}\n".encode(append_enc)
    try:
        rc.parent.mkdir(parents=True, exist_ok=True)
        with rc.open("ab") as fh:  # binary: no TextIOWrapper BOM injection
            fh.write(payload)
    except OSError as exc:
        raise InstallError(_manual_hint(rc, line, exc)) from exc
    return True


def _manual_hint(rc: Path, line: str, exc: Exception) -> str:
    return f"could not update {rc} ({exc}) — add this line yourself: {line}"


def _remove_once(rc: Path, line: str) -> bool:
    """Remove the exact *line* from *rc*; True if the file changed.

    The mirror of `_append_once`, encoding-faithful the same way: the file's
    own BOM (if any) is kept, the body re-encoded in the matching BOM-free
    encoding — so uninstalling from a UTF-16 PowerShell profile leaves it
    UTF-16 with exactly one BOM, and a latin-1 rc round-trips untouched.
    """
    try:
        raw = rc.read_bytes() if rc.exists() else b""
    except OSError as exc:
        raise InstallError(
            f"could not update {rc} ({exc}) — remove this line yourself: {line}"
        ) from exc
    if not raw:
        return False
    read_enc, write_enc = _sniff_encoding(raw)
    existing = raw.decode(read_enc, errors="replace")
    if line not in existing:
        return False
    boms = tuple(bom for bom, _, _ in _encoding.BOM_ENCODINGS)
    bom = next((b for b in boms if raw.startswith(b)), b"")
    kept = [ln for ln in existing.splitlines() if ln.strip() != line.strip()]
    body = "\n".join(kept) + ("\n" if kept else "")
    try:
        rc.write_bytes(bom + body.encode(write_enc))
    except OSError as exc:
        raise InstallError(
            f"could not update {rc} ({exc}) — remove this line yourself: {line}"
        ) from exc
    return True


def _zsh_rc() -> Path:
    """The `.zshrc` zsh actually reads — under `$ZDOTDIR` when set (D11)."""
    zdotdir = os.environ.get("ZDOTDIR")
    base = Path(zdotdir) if zdotdir else Path.home()
    return base / ".zshrc"


def _bash_rcs() -> list[Path]:
    """The rc files bash actually reads for completion to activate (D11).

    `.bashrc` covers interactive non-login shells. On macOS, Terminal opens
    *login* shells, which read a login profile (`.bash_profile`/`.bash_login`/
    `.profile`) and not `.bashrc` — so append there too, to the first existing
    one, creating `.bash_profile` only when none exists (never shadowing an
    existing `.profile`).
    """
    home = Path.home()
    rcs = [home / ".bashrc"]
    if sys.platform == "darwin":
        logins = [home / ".bash_profile", home / ".bash_login", home / ".profile"]
        existing = next((p for p in logins if p.exists()), None)
        rcs.append(existing or home / ".bash_profile")
    return rcs


_PROC_NAMES = {
    "bash": "bash",
    "zsh": "zsh",
    "fish": "fish",
    "nu": "nushell",
    "pwsh": "pwsh",
    "powershell": "pwsh",
}


def detect_shell() -> str | None:
    """Best-effort, zero-dependency detection of the invoking shell.

    Walks the parent-process tree (the immediate parent is often `uv`, not
    the shell) looking for a known shell name — what shellingham does for
    typer, without the dependency. Windows has no `ps`, so the PowerShell
    tell there is the `PSModulePath` variable it exports to children. Falls
    back to the login shell in `$SHELL`; returns `None` when nothing is
    confidently recognised.
    """
    if os.name == "nt":
        # git-bash (and MSYS2) export MSYSTEM — checked first, because
        # PowerShell's PSModulePath is machine-level environment and is set
        # inside git-bash too. Without this a git-bash user is told "pwsh",
        # which is a small lie that installs the wrong hook.
        if os.environ.get("MSYSTEM"):
            return "bash"
        # PSModulePath still over-claims from cmd.exe — acceptable, because
        # cmd has no completion mechanism and a PowerShell install is the
        # most useful answer on that box. (Real spelling kept; Windows env
        # lookup is case-insensitive anyway.)
        return "pwsh" if os.environ.get("PSModulePath") else None  # noqa: SIM112
    return _detect_posix()


def _detect_posix() -> str | None:
    pid = os.getppid()
    for _ in range(10):
        if pid <= 1:
            break
        try:
            out = subprocess.run(
                ["ps", "-p", str(pid), "-o", "ppid=,comm="],
                capture_output=True,
                text=True,
                timeout=5,
            )
        except (OSError, subprocess.TimeoutExpired):
            break
        line = out.stdout.strip()
        if out.returncode != 0 or not line:
            break
        ppid, _, comm = line.partition(" ")
        # A login shell reports as "-zsh"; comm may be a full path.
        name = Path(comm.strip()).name.lstrip("-")
        if name in _PROC_NAMES:
            return _PROC_NAMES[name]
        try:
            pid = int(ppid)
        except ValueError:
            break
    login = Path(os.environ.get("SHELL", "")).name
    return _PROC_NAMES.get(login)


def _ask_shell(candidates: tuple[str, ...], args: list[str]) -> str | None:
    """Run the first available *candidates* binary and return its stdout."""
    for exe in candidates:
        binary = shutil.which(exe)
        if binary is None:
            continue
        try:
            out = subprocess.run(
                [binary, *args], capture_output=True, text=True, timeout=30
            )
        except (OSError, subprocess.TimeoutExpired):
            continue
        if out.returncode == 0 and out.stdout.strip():
            return out.stdout.strip()
    return None


def _pwsh_profiles() -> list[Path]:
    """Every distinct `$PROFILE` among the PowerShells on PATH.

    PowerShell 7 (`pwsh`) and Windows PowerShell (`powershell`) keep
    *different* profile files; on a machine with both, completion should work
    in whichever one the user opens — so the installer targets them all.
    """
    profiles: list[Path] = []
    for exe in ("pwsh", "powershell"):
        path = _ask_shell((exe,), ["-NoProfile", "-Command", "$PROFILE"])
        if path is not None and Path(path) not in profiles:
            profiles.append(Path(path))
    if not profiles:
        raise InstallError(
            "pwsh (or powershell) not found on PATH — install PowerShell first"
        )
    return profiles


def _nu_config_path() -> Path:
    """The config file nushell itself reports (`$nu.config-path`)."""
    path = _ask_shell(("nu",), ["-c", "$nu.config-path"])
    if path is None:
        raise InstallError("nu not found on PATH — install nushell first")
    return Path(path)


def _bash_path(path: Path | str, *, windows: bool | None = None) -> str:
    """*path* as the bash on this platform can read it.

    A Windows path is unusable inside a bash rc: backslashes are escapes,
    so `source C:\\Users\\me\\...` silently sources nothing. git-bash
    understands the MSYS spelling — `/c/Users/me/...` — which is what this
    produces; elsewhere the path is already right.

    *windows* is explicit so the translation can be tested from any
    platform: string surgery only, because building a Windows `Path` on a
    POSIX box is impossible and monkeypatching `os.name` to pretend
    otherwise breaks pathlib for everything else in the process.
    """
    if windows is None:
        windows = os.name == "nt"
    text = str(path)
    if not windows:
        return text
    text = text.replace("\\", "/")
    drive, colon, rest = text.partition(":")
    if colon and len(drive) == 1:
        return f"/{drive.lower()}{rest}"
    return text


def install(shell: str, prog: str) -> list[str]:
    """Install completion for *shell*; return the lines to tell the user.

    Raises `KeyError` for an unsupported shell and `InstallError` when the
    shell itself is missing — the caller owns the taught error (it knows the
    brand).
    """
    script = script_for(shell, prog)

    if shell == "fish":
        target = _paths.config_home() / "fish" / "completions" / f"{prog}.fish"
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(script, encoding="utf-8")
        return [
            f"installed {target}",
            "fish picks it up automatically — start a new shell and TAB away.",
        ]

    target = hook_path(shell, prog)
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(script, encoding="utf-8")
    if shell == "pwsh":
        # The hook runs on PowerShell 5+ unchanged, so it goes into every
        # PowerShell profile present — both shells complete, whoever answers.
        hooks = [(rc, f'. "{target}"') for rc in _pwsh_profiles()]
    elif shell == "nushell":
        hooks = [(_nu_config_path(), f'source "{target}"')]
    elif shell == "zsh":
        hooks = [(_zsh_rc(), f"source {_bash_path(target)}")]
    else:  # bash — git-bash included, hence the MSYS-spelled path
        hooks = [(rc, f"source {_bash_path(target)}") for rc in _bash_rcs()]
    lines = [f"installed {target}"]
    for rc, line in hooks:
        if _append_once(rc, line):
            lines.append(f"added `{line}` to {rc}")
        else:
            lines.append(f"{rc} already sources it")
    lines.append("restart your shell (or source the rc file) and TAB away.")
    return lines


def hook_path(shell: str, prog: str) -> Path:
    """Where *shell* keeps *prog*'s completion script.

    One spelling, because three copies of it is what the comment in
    `uninstall` used to warn about: install writing one path and uninstall
    computing another leaves the script removed and its rc line behind,
    sourcing nothing. fish owns its own conventional directory; everyone
    else gets `<data home>/<prog>/completion.<suffix>`.

    Note this is keyed by the **command name**, not the config stem, so it
    sits *beside* `data_dir()` rather than inside it — `~/.local/share/fm/`
    next to `~/.local/share/footman/`. Anything clearing a runner's
    leavings has to know that.
    """
    if shell == "fish":
        return _paths.config_home() / "fish" / "completions" / f"{prog}.fish"
    suffix = {"pwsh": "ps1", "nushell": "nu"}.get(shell, shell)
    return _paths.data_home() / prog / f"completion.{suffix}"


def uninstall(shell: str, prog: str) -> list[str]:
    """Remove *shell*'s completion for *prog*: the script file and the rc line.

    The mirror of `install()`, idempotent the same way — uninstalling what was
    never installed reports what it looked for rather than failing. When the
    shell itself is gone (its rc/profile can't be located any more), the
    script file is still removed and the leftover line is named, so finishing
    by hand is one paste.
    """
    if shell == "fish":
        target = hook_path(shell, prog)
        if target.exists():
            target.unlink()
            return [f"removed {target}"]
        return [f"nothing to remove ({target} was not installed)"]

    target = hook_path(shell, prog)
    hook = {
        "pwsh": f'. "{target}"',
        "nushell": f'source "{target}"',
    }.get(shell, f"source {_bash_path(target)}")

    lines: list[str] = []
    if target.exists():
        target.unlink()
        with contextlib.suppress(OSError):  # only when nothing else lives there
            target.parent.rmdir()
        lines.append(f"removed {target}")

    try:
        if shell == "pwsh":
            rcs = _pwsh_profiles()
        elif shell == "nushell":
            rcs = [_nu_config_path()]
        elif shell == "zsh":
            rcs = [_zsh_rc()]
        else:  # bash
            rcs = _bash_rcs()
    except InstallError as exc:
        lines.append(
            f"could not locate the rc file ({exc}) — "
            f"if it still sources the hook, remove this line yourself: {hook}"
        )
        return lines

    for rc in rcs:
        if _remove_once(rc, hook):
            lines.append(f"removed `{hook}` from {rc}")
    if not lines:
        lines.append(f"nothing to remove ({target} was not installed)")
    return lines
