"""Provenance: which channel owns a file, and where to edit it.

One classifier answers for any path; everything else serialises its
answer. ``fm explain <path>`` prints it. The templates carry their
own headers (parameterised, so ``copier update`` sees them as
template lines, never local edits) and the emitters open every
generated file with theirs, so the answer rides the file wherever
comments are possible. Materialised copies are never injected:
override detection depends on the copy staying byte-identical to
its source, so those files, and comment-hostile ones, are explain's
territory alone. Shipped layer content carries its header through
the provenance lint, whose ``--fix`` writes the computed text.
"""

from __future__ import annotations

import os
import subprocess
from dataclasses import dataclass
from pathlib import Path
from typing import Annotated

import footman
from footman import Arg, ask, doc, fail, suggest, task

from livery.workshop._layers import layer_names, workspace_root

#: The project render's managed names, judged by the drift gate. The
#: template tree is the truth; this list is the offline copy a wheel
#: instance can answer from, pinned against the tree by test.
PROJECT_RENDERED = ("pyproject.toml", "tasks.py", ".gitignore")

#: Comment leaders by suffix, and by exact name for suffixless files.
#: A type absent from both tables cannot carry a header and is
#: explain's territory alone.
_BY_SUFFIX = {
    ".py": "#",
    ".toml": "#",
    ".yml": "#",
    ".yaml": "#",
    ".sh": "#",
    ".cfg": "#",
    ".ini": "#",
    ".md": "html",
}
_BY_NAME = {".gitignore": "#", "CODEOWNERS": "#"}


def comment_style(path: Path) -> str:
    """The comment leader for *path*: ``#``, ``html``, or empty."""
    return _BY_NAME.get(path.name, _BY_SUFFIX.get(path.suffix, ""))


#: Phrases that mark a header as machine-written, for refresh.
_MARKERS = (
    "the template channel",
    "the workshop from workshop.toml",
    "Seeded from",
    "layer content",
)


def format_header(lines: tuple[str, ...], style: str) -> str:
    """The header *lines* as one comment block in *style*."""
    if style == "html":
        body = "".join(f"     {line}\n" for line in lines[1:])
        return f"<!-- {lines[0]}\n{body}-->\n"
    return "".join(f"# {line}\n" for line in lines)


def generated_header(style: str) -> str:
    """The header every emitted artifact opens with."""
    prog = footman.prog()
    lines = (
        "Generated by the workshop from workshop.toml; the gate keeps",
        "it matching. Edit the contract (or the emitters) and run",
        f"`{prog} template.apply`; an edit here is drift.",
    )
    return format_header(lines, style)


def content_header(layer: str, style: str) -> str:
    """The header shipped layer content carries, lint-enforced."""
    lines = (
        f"Shipped as {layer} layer content, delivered to the workspace",
        "by the sync verb. Edit this copy in the layer and release it;",
        "an edited delivered copy is a local override, kept and named.",
    )
    return format_header(lines, style)


def _insertion_point(text: str, path: Path) -> int:
    """Where a header lands: after a shebang or markdown frontmatter."""
    if text.startswith("#!"):
        return text.find("\n") + 1
    if path.suffix == ".md" and text.startswith("---\n"):
        end = text.find("\n---\n", 4)
        if end != -1:
            return end + len("\n---\n")
    return 0


def inject(path: Path, header: str) -> None:
    """Open *path* with *header*, replacing a stale machine header."""
    text = path.read_text(encoding="utf-8")
    text = strip_header(text, path)
    at = _insertion_point(text, path)
    path.write_text(text[:at] + header + text[at:], encoding="utf-8", newline="\n")


def has_header(path: Path, header: str) -> bool:
    """Whether *path* already opens with *header* (shebang-tolerant)."""
    text = path.read_text(encoding="utf-8")
    at = _insertion_point(text, path)
    return text[at:].startswith(header)


def strip_header(text: str, path: Path) -> str:
    """*text* with a machine-written header removed, others kept."""
    at = _insertion_point(text, path)
    head, tail = text[:at], text[at:]
    style = comment_style(path)
    if style == "html":
        if tail.startswith("<!--") and "-->" in tail:
            block, _, rest = tail.partition("-->\n")
            if any(marker in block for marker in _MARKERS):
                return head + rest.lstrip("\n")
        return text
    lines = tail.splitlines(keepends=True)
    block_end = 0
    for line in lines:
        if line.startswith("#") and not line.startswith("#!"):
            block_end += 1
        else:
            break
    block = "".join(lines[:block_end])
    if any(marker in block for marker in _MARKERS):
        rest = "".join(lines[block_end:]).lstrip("\n")
        return head + rest
    return text


@dataclass(frozen=True)
class Provenance:
    """One file's answer: the channel, the source, the edit path.

    Attributes:
        channel: The owning channel's short name.
        source: Where the content comes from.
        edit: What to change, and through which verb.
    """

    channel: str
    source: str
    edit: str


def _materialised(root: Path, relative: Path) -> Provenance | None:
    """The answer for a path the sync verb delivers, or None."""
    from livery.workshop._materialise import _is_link, _read_manifest

    prog = footman.prog()
    parts = relative.parts
    if parts[0] == ".workshop":
        return Provenance(
            "layer fragment",
            f"a mounted layer's content/fragments/{relative.name}",
            f"edit the layer's copy; `{prog} sync` rewrites this one wholesale",
        )
    if parts[0] == "CLAUDE.md" and len(parts) == 1:
        return Provenance(
            "sync stub",
            f"written by `{prog} sync` from the mounted layers' fragments",
            "edit CLAUDE.project.md, never this file",
        )
    if parts[0] != ".claude" or len(parts) < 2:
        return None
    if parts[1] in ("skills", "hooks") and len(parts) >= 3:
        home = root / ".claude" / parts[1]
        entry = home / parts[2]
        manifest = _read_manifest(home)
        if _is_link(entry) or parts[2] in manifest:
            return Provenance(
                "materialised",
                f"a mounted layer's content/{parts[1]}/{parts[2]}",
                "edit the layer's copy; an edit here becomes a local"
                " override on the next sync",
            )
        return Provenance(
            "local override" if _shipped(parts[1], parts[2]) else "yours",
            "this repository",
            "edit directly; it commits like any repo file",
        )
    if parts[1] == "settings.json":
        manifest = _read_manifest(root / ".claude")
        if "settings.json" in manifest:
            return Provenance(
                "materialised",
                "a mounted layer's content/settings.json",
                "edit the layer's copy; an edit here becomes a local"
                " override on the next sync",
            )
        return Provenance(
            "local override" if _shipped("", "settings.json") else "yours",
            "this repository",
            "edit directly; it commits like any repo file",
        )
    return None


def _shipped(subdir: str, name: str) -> bool:
    """Whether any mounted layer ships this content entry."""
    from livery.workshop._sync import _layer_content

    for layer in layer_names():
        content = _layer_content(layer)
        if content is None:
            continue
        candidate = content / subdir / name if subdir else content / name
        if candidate.exists():
            return True
    return False


def classify(root: Path, relative: Path) -> Provenance:
    """The provenance of *relative* inside *root*; "yours" when no channel claims it.

    *relative* is taken lexically, never resolved: a materialised
    link classifies as the delivered entry it is, not as the wheel
    path it points into.
    """
    from livery.workshop._ci_generate import generate
    from livery.workshop._governance import codeowners_file
    from livery.workshop._templates import PROJECT_SEEDS, template_source

    prog = footman.prog()
    posix = relative.as_posix()

    delivered = _materialised(root, relative)
    if delivered is not None:
        return delivered

    generated = set(generate(root))
    owners = codeowners_file(root)
    if owners is not None:
        generated.add(owners.path)
    if posix in generated:
        return Provenance(
            "generated",
            "the workshop emitters, from workshop.toml",
            f"edit workshop.toml (or the emitters) and run `{prog} template.apply`",
        )

    source = template_source(root)
    if posix in PROJECT_RENDERED:
        return Provenance(
            "rendered",
            f"the template channel ({source}, project kind)",
            f"edit the template source and run `{prog} template.apply`",
        )
    if posix in PROJECT_SEEDS:
        return Provenance(
            "seed",
            f"seeded at birth from the template channel ({source})",
            "yours: edit directly; the template never rewrites it",
        )
    if posix == ".copier-answers.yml":
        return Provenance(
            "receipts",
            "machine-managed identity and template provenance",
            f"never by hand; `{prog} new.package` and the update wave write it",
        )
    if relative.name == "workshop.toml":
        return Provenance(
            "contract",
            "the workspace contract, config-as-code",
            "edit directly and merge; governance applies itself on main",
        )
    if posix == ".repo.env":
        return Provenance(
            "environment",
            "the committed rung of the env cascade",
            f"`{prog} env.set KEY --scope=repo`, or edit directly",
        )
    if posix == "uv.lock":
        return Provenance(
            "toolchain",
            "uv's lockfile",
            "`uv lock` (or the update wave); never by hand",
        )
    if len(relative.parts) > 2 and relative.parts[0] == "packages":
        member = Path(*relative.parts[:2])
        rest = Path(*relative.parts[2:]).as_posix()
        if rest == "cliff.toml":
            return Provenance(
                "rendered",
                f"the template channel ({source}, package-python kind)",
                f"edit the template source and run `{prog} template.apply`",
            )
        if rest == ".copier-answers.yml":
            return Provenance(
                "receipts",
                "machine-managed package identity",
                "never by hand; the render wrote it",
            )
        if "/content/" in rest:
            return Provenance(
                "layer content",
                f"{member.as_posix()}: what this layer ships; the"
                " provenance lint keeps its header",
                f"edit directly here; `{prog} sync` delivers it",
            )
        return Provenance(
            "yours",
            f"{member.as_posix()}: the package's own file since its birth",
            "edit directly",
        )
    return Provenance("yours", "this repository", "edit directly")


def _tracked_paths() -> list[str]:
    """Git-tracked paths, the completion surface for explain."""
    root = workspace_root()
    if root is None:
        return []
    listing = subprocess.run(
        ["git", "ls-files"],
        cwd=root,
        capture_output=True,
        text=True,
        check=False,
    )
    return listing.stdout.splitlines()


@task
def explain(
    path: Annotated[
        Arg[str],
        ask(),
        suggest(_tracked_paths, strict=False),
        doc("the file to explain, relative to the workspace root"),
    ] = "",
) -> None:
    """Name the channel that owns a file, its source, and the edit path.

    Every answer has the same three lines; a file no channel claims is
    yours, which is the honest default, not an error.
    """
    if not path:
        fail(f"name a file: `{footman.prog()} explain pyproject.toml`")
    root = workspace_root()
    if root is None:
        fail("no workspace: no workshop.toml above the working directory")
    raw = Path(path)
    if raw.is_absolute():
        try:
            raw = raw.relative_to(root)
        except ValueError:
            fail(f"{path} is outside this workspace")
    relative = Path(os.path.normpath(str(raw)))
    if not relative.parts or relative.parts[0] == "..":
        fail(f"{path} is outside this workspace")
    answer = classify(root, relative)
    print(f"  {relative.as_posix()}")
    print(f"    channel: {answer.channel}")
    print(f"    source: {answer.source}")
    print(f"    edit: {answer.edit}")


def _content_trees(root: Path) -> list[tuple[str, Path]]:
    """Each workspace package's shipped content tree, with its layer name."""
    trees = []
    for src in sorted(root.glob("packages/*/src")):
        for content in sorted(src.rglob("content")):
            if not content.is_dir():
                continue
            layer = ".".join(content.parent.relative_to(src).parts)
            trees.append((layer, content))
    return trees


def content_lint(root: Path, *, fix: bool = False) -> list[str]:
    """Layer content files missing their computed header; ``fix`` writes it.

    Only the workspace's own packages are linted: an installed
    layer's content is its home repository's to keep. Files without
    a comment syntax are exempt; explain still answers for them.
    """
    problems = []
    for layer, content in _content_trees(root):
        for path in sorted(content.rglob("*")):
            if not path.is_file() or "__pycache__" in path.parts:
                continue
            style = comment_style(path)
            if not style:
                continue
            header = content_header(layer, style)
            if has_header(path, header):
                continue
            if fix:
                inject(path, header)
                problems.append(f"{path.relative_to(root)}: header written")
            else:
                problems.append(f"{path.relative_to(root)}: missing its header")
    return problems


@task(name="provenance")
def provenance_check(
    fix: Annotated[bool, doc("write the computed headers in place")] = False,
) -> None:
    """Check shipped layer content opens with its provenance header.

    Part of the gate. Nobody composes a header by hand: ``--fix``
    writes the computed text, and the render and emitters inject
    theirs into everything they write.
    """
    root = workspace_root()
    if root is None:
        fail("no workspace: no workshop.toml above the working directory")
    findings = content_lint(root, fix=fix)
    for line in findings:
        print(f"  {line}")
    if findings and not fix:
        fail(
            "layer content is missing provenance headers: run"
            f" `{footman.prog()} check --fix` to write them"
        )
