"""Provenance: which channel owns a file, and where to edit it.

One classifier answers for any path; everything else serialises its
answer. ``fm explain <path>`` prints it. The fragment engine and the
emitters open every file they write with a header, so the answer rides
the file wherever comments are possible. Materialised copies are never injected:
override detection depends on the copy staying byte-identical to
its source, so those files, and comment-hostile ones, are explain's
territory alone. Shipped extension content carries its header through
the provenance lint, whose ``--fix`` writes the computed text.
"""

from __future__ import annotations

import os
from pathlib import Path
from typing import Annotated

import livery.footman as footman
from livery.footman import Arg, ask, doc, fail, suggest, task
from livery.workshop._categories import (
    ChannelRule,
    Provenance,
    category_of,
    channel_of,
    register_channels,
)
from livery.workshop._extensions import stack_names, workspace_root
from livery.workshop._packages import Package

#: Comment leaders by suffix, and by exact name for suffixless files.
#: A type absent from both tables cannot carry a header and is
#: explain's territory alone.
_BY_SUFFIX = {
    ".py": "#",
    ".toml": "#",
    ".yml": "#",
    ".yaml": "#",
    ".sh": "#",
    ".cfg": "#",
    ".ini": "#",
    ".md": "html",
}
_BY_NAME = {".gitignore": "#", ".gitattributes": "#", "CODEOWNERS": "#"}


def comment_style(path: Path) -> str:
    """The comment leader for *path*: ``#``, ``//``, ``html``, or empty.

    The editor's ``.vscode/settings.json`` is JSON with comments, the
    one JSON the render owns; every other JSON carries no header.
    """
    if path.name == "settings.json" and path.parent.name == ".vscode":
        return "//"
    return _BY_NAME.get(path.name, _BY_SUFFIX.get(path.suffix, ""))


#: Phrases that mark a header as machine-written, for refresh.
_MARKERS = (
    "the template channel",
    "the workshop from workshop.toml",
    "Seeded from",
    "extension content",
)


def format_header(lines: tuple[str, ...], style: str) -> str:
    """The header *lines* as one comment block in *style*."""
    if style == "html":
        body = "".join(f"     {line}\n" for line in lines[1:])
        return f"<!-- {lines[0]}\n{body}-->\n"
    return "".join(f"{style} {line}\n" for line in lines)


def generated_header(style: str) -> str:
    """The header every emitted artifact opens with."""
    prog = footman.prog()
    lines = (
        "Generated by the workshop from workshop.toml; the gate keeps",
        "it matching. Edit the contract (or the emitters) and run",
        f"`{prog} sync`; an edit here is drift.",
    )
    return format_header(lines, style)


def content_header(extension: str, style: str) -> str:
    """The header shipped extension content carries, lint-enforced."""
    lines = (
        f"Shipped as {extension} extension content, delivered to the workspace",
        "by the sync verb. Edit this copy in the extension and release it;",
        "an edited delivered copy is a local override, kept and named.",
    )
    return format_header(lines, style)


def _insertion_point(text: str, path: Path) -> int:
    """Where a header lands: after a shebang or markdown frontmatter."""
    if text.startswith("#!"):
        return text.find("\n") + 1
    if path.suffix == ".md" and text.startswith("---\n"):
        end = text.find("\n---\n", 4)
        if end != -1:
            return end + len("\n---\n")
    return 0


def inject(path: Path, header: str) -> None:
    """Open *path* with *header*, replacing a stale machine header."""
    text = path.read_text(encoding="utf-8")
    text = strip_header(text, path)
    at = _insertion_point(text, path)
    path.write_text(text[:at] + header + text[at:], encoding="utf-8", newline="\n")


def has_header(path: Path, header: str) -> bool:
    """Whether *path* already opens with *header* (shebang-tolerant)."""
    text = path.read_text(encoding="utf-8")
    at = _insertion_point(text, path)
    return text[at:].startswith(header)


def strip_header(text: str, path: Path) -> str:
    """*text* with a machine-written header removed, others kept."""
    at = _insertion_point(text, path)
    head, tail = text[:at], text[at:]
    style = comment_style(path)
    if style == "html":
        if tail.startswith("<!--") and "-->" in tail:
            block, _, rest = tail.partition("-->\n")
            if any(marker in block for marker in _MARKERS):
                return head + rest.lstrip("\n")
        return text
    lines = tail.splitlines(keepends=True)
    block_end = 0
    for line in lines:
        if line.startswith("#") and not line.startswith("#!"):
            block_end += 1
        else:
            break
    block = "".join(lines[:block_end])
    if any(marker in block for marker in _MARKERS):
        rest = "".join(lines[block_end:]).lstrip("\n")
        return head + rest
    return text


def _materialised(root: Path, relative: Path) -> Provenance | None:
    """The answer for a path the sync verb delivers, or None."""
    from livery.workshop._fragment_engine import local_receipts
    from livery.workshop._materialise import _is_link

    prog = footman.prog()
    receipted = local_receipts(root)
    parts = relative.parts
    if parts[0] == ".workshop":
        if parts[1:2] == ("fragments",):
            return Provenance(
                "extension fragment",
                f"a mounted extension's content/fragments/{relative.name}, or a"
                " render from its registries",
                f"edit the extension's copy; an edit here is a local override"
                f" `{prog} sync` keeps and names",
            )
        # Everything else under .workshop is this checkout's own: the
        # tool receipts, the stub receipt, the linked binaries. None of
        # them has an edit path, and
        # calling them extension fragments was a lie the directory's older
        # shape made easy to tell.
        return Provenance(
            "checkout state",
            f"written by `{prog} sync` for this checkout alone",
            "nothing to edit here; delete it and the next sync writes it again",
        )
    if parts[0] == "CLAUDE.md" and len(parts) == 1:
        return Provenance(
            "sync stub",
            f"written by `{prog} sync` from the mounted extensions' fragments",
            "edit CLAUDE.project.md, never this file",
        )
    if parts[0] != ".claude" or len(parts) < 2:
        return None
    if parts[1] in ("skills", "hooks") and len(parts) >= 3:
        entry = root / ".claude" / parts[1] / parts[2]
        if _is_link(entry) or f".claude/{parts[1]}/{parts[2]}" in receipted:
            return Provenance(
                "materialised",
                f"a mounted extension's content/{parts[1]}/{parts[2]}",
                "edit the extension's copy; an edit here becomes a local"
                " override on the next sync",
            )
        return Provenance(
            "local override" if _shipped(parts[1], parts[2]) else "yours",
            "this repository",
            "edit directly; it commits like any repo file",
        )
    if parts[1] == "settings.json":
        if ".claude/settings.json" in receipted:
            return Provenance(
                "materialised",
                "a mounted extension's content/settings.json",
                "edit the extension's copy; an edit here becomes a local"
                " override on the next sync",
            )
        return Provenance(
            "local override" if _shipped("", "settings.json") else "yours",
            "this repository",
            "edit directly; it commits like any repo file",
        )
    return None


def _shipped(subdir: str, name: str) -> bool:
    """Whether any mounted extension ships this content entry."""
    from livery.workshop._extensions import extension_content

    for extension in stack_names():
        content = extension_content(extension)
        if content is None:
            continue
        candidate = content / subdir / name if subdir else content / name
        if candidate.exists():
            return True
    return False


def emitted_paths(root: Path) -> frozenset[str]:
    """The paths the workshop emitters write for *root*, the owners file included.

    One emission is a full render of every workflow, the site
    configuration, and the entry script; a caller classifying many
    paths computes this once and hands it to
    [livery.workshop._provenance.classify][].
    """
    from livery.workshop._ci_generate import generate
    from livery.workshop._governance import codeowners_file

    generated = set(generate(root))
    owners = codeowners_file(root)
    if owners is not None:
        generated.add(owners.path)
    return frozenset(generated)


def classify(
    root: Path, relative: Path, *, emitted: frozenset[str] | None = None
) -> Provenance:
    """The provenance of *relative* inside *root*; "yours" when no channel claims it.

    *relative* is taken lexically, never resolved: a materialised
    link classifies as the delivered entry it is, not as the wheel
    path it points into. *emitted* is the emitters' path set from
    [livery.workshop._provenance.emitted_paths][]; a caller with many
    paths passes one set rather than paying an emission per path.
    The answer comes from the channel registry, the builtin ladder
    below and whatever an extension registered beside it, highest rank
    first.
    """
    found = channel_of(root, relative, emitted=emitted)
    if found is not None:
        return found.provenance
    return Provenance("yours", "this repository", "edit directly")


def _rule_materialised(
    root: Path, relative: Path, emitted: frozenset[str] | None
) -> Provenance | None:
    del emitted
    return _materialised(root, relative)


def _rule_generated(
    root: Path, relative: Path, emitted: frozenset[str] | None
) -> Provenance | None:
    prog = footman.prog()
    generated = emitted_paths(root) if emitted is None else emitted
    if relative.as_posix() not in generated:
        return None
    return Provenance(
        "generated",
        "the workshop emitters, from workshop.toml",
        f"edit workshop.toml (or the emitters) and run `{prog} sync`",
    )


def _rule_composed(
    root: Path, relative: Path, emitted: frozenset[str] | None
) -> Provenance | None:
    del emitted
    from livery.workshop._fragment_engine import PACKAGE_PREFIX
    from livery.workshop._packages import member_depth
    from livery.workshop._shipped_files import shipped

    fragments, _order = shipped(root)
    # A package's file is composed from the `package/` fragments.
    depth = member_depth(root, relative)
    inner = PACKAGE_PREFIX + Path(*relative.parts[depth:]).as_posix() if depth else ""
    owners = [
        fragment.owner
        for fragment in fragments
        if fragment.target in (relative.as_posix(), inner)
    ]
    if not owners:
        return None
    prog = footman.prog()
    return Provenance(
        "composed",
        f"the fragment engine, from {', '.join(dict.fromkeys(owners))}",
        f"edit inside its regions, or the extension's lines, and run `{prog} sync`",
    )


def _rule_seed(
    root: Path, relative: Path, emitted: frozenset[str] | None
) -> Provenance | None:
    del emitted
    del root
    from livery.workshop._seeds import PROJECT_SEEDS

    if relative.as_posix() not in PROJECT_SEEDS:
        return None
    return Provenance(
        "seed",
        "written at birth from the extensions' seeds",
        "yours: edit directly; nothing rewrites it",
    )


def _rule_receipts(
    root: Path, relative: Path, emitted: frozenset[str] | None
) -> Provenance | None:
    del root, emitted
    if relative.as_posix() != ".workshop-rendered":
        return None
    prog = footman.prog()
    return Provenance(
        "receipts",
        "what the fragment engine last wrote into the workspace's files",
        f"never by hand; `{prog} sync` keeps it",
    )


def _rule_contract(
    root: Path, relative: Path, emitted: frozenset[str] | None
) -> Provenance | None:
    del root, emitted
    if relative.name != "workshop.toml":
        return None
    return Provenance(
        "contract",
        "the workspace contract, config-as-code",
        "edit directly and merge; governance applies itself on main",
    )


def _rule_environment(
    root: Path, relative: Path, emitted: frozenset[str] | None
) -> Provenance | None:
    del root, emitted
    if relative.as_posix() != ".repo.env":
        return None
    prog = footman.prog()
    return Provenance(
        "environment",
        "the committed rung of the env cascade",
        f"`{prog} env.set KEY --scope=repo`, or edit directly",
    )


def _rule_toolchain(
    root: Path, relative: Path, emitted: frozenset[str] | None
) -> Provenance | None:
    del root, emitted
    if relative.as_posix() != "uv.lock":
        return None
    return Provenance(
        "toolchain",
        "uv's lockfile",
        "`uv lock` (or the update wave); never by hand",
    )


def _rule_member(
    root: Path, relative: Path, emitted: frozenset[str] | None
) -> Provenance | None:
    """A package's own files: its changelog config, its receipts, its content."""
    del emitted
    from livery.workshop._packages import member_depth

    depth = member_depth(root, relative)
    if not depth:
        return None
    prog = footman.prog()
    member = Path(*relative.parts[:depth])
    rest = Path(*relative.parts[depth:]).as_posix()
    if rest == ".workshop-rendered":
        return Provenance(
            "receipts",
            "what the render wrote into this package for the checks' files",
            f"never by hand; `{prog} sync` keeps it",
        )
    from livery.workshop._fragments import package_files

    if rest in package_files():
        return Provenance(
            "rendered",
            "a check record's fragment for this package's kind",
            f"edit the record's fragment and run `{prog} sync`; a"
            " deeper file with InheritParentConfig carries this package's own lines",
        )
    if "/content/" in rest:
        return Provenance(
            "extension content",
            f"{member.as_posix()}: what this extension ships; the"
            " provenance lint keeps its header",
            f"edit directly here; `{prog} sync` delivers it",
        )
    return Provenance(
        "yours",
        f"{member.as_posix()}: the package's own file since its birth",
        "edit directly",
    )


# The builtin ladder as ranked rules: an extension registers its own beside
# them, at the rank that says where it stands.
register_channels(
    [
        ChannelRule("materialised", _rule_materialised, 100, "livery.workshop"),
        ChannelRule("generated", _rule_generated, 90, "livery.workshop"),
        ChannelRule("composed", _rule_composed, 85, "livery.workshop"),
        ChannelRule("seed", _rule_seed, 70, "livery.workshop"),
        ChannelRule("receipts", _rule_receipts, 60, "livery.workshop"),
        ChannelRule("contract", _rule_contract, 50, "livery.workshop"),
        ChannelRule("environment", _rule_environment, 40, "livery.workshop"),
        ChannelRule("toolchain", _rule_toolchain, 30, "livery.workshop"),
        ChannelRule("member", _rule_member, 20, "livery.workshop"),
    ]
)


def _tracked_paths() -> list[str]:
    """Git-tracked paths, the completion surface for explain."""
    root = workspace_root()
    if root is None:
        return []
    import livery.toolroom.tools as tools

    listing = tools.git.opts(cwd=root, nofail=True, recorded=False)("ls-files")
    return listing.stdout.splitlines()


@task
def explain(
    path: Annotated[
        Arg[str],
        ask(),
        suggest(_tracked_paths, strict=False),
        doc("the file to explain, relative to the workspace root"),
    ] = "",
) -> None:
    """Name the channel that owns a file, its source, and the edit path.

    Every answer has the same three lines; a file no channel claims is
    yours, which is the honest default, not an error.
    """
    if not path:
        fail(f"name a file: `{footman.prog()} explain pyproject.toml`")
    root = workspace_root()
    if root is None:
        fail("no workspace: no workshop.toml above the working directory")
    raw = Path(path)
    if raw.is_absolute():
        try:
            raw = raw.relative_to(root)
        except ValueError:
            fail(f"{path} is outside this workspace")
    relative = Path(os.path.normpath(str(raw)))
    if not relative.parts or relative.parts[0] == "..":
        fail(f"{path} is outside this workspace")
    for line in describe(root, relative):
        print(line)


def describe(root: Path, relative: Path) -> list[str]:
    """The lines ``fm explain`` prints for *relative*: category, channel, claims."""
    from livery.workshop._docs_contract import site_reads
    from livery.workshop._packages import discover_packages

    packages = discover_packages(root) if (root / "packages").is_dir() else ()
    unit, inside = unit_of(root, packages, relative.as_posix())
    lines = [f"  {relative.as_posix()}"]
    if unit is not None:
        category = category_of(unit, inside)
        lines.append(f"    category: {category.name} ({category.supplier})")
    found = channel_of(root, relative)
    answer = found.provenance if found is not None else classify(root, relative)
    supplier = found.supplier if found is not None else "livery.workshop"
    lines.append(f"    channel: {answer.channel} ({supplier})")
    lines.append(f"    source: {answer.source}")
    lines.append(f"    edit: {answer.edit}")
    from livery.workshop._checks import claimants

    claims = list(claimants(unit, inside)) if unit is not None else []
    if site_reads(root, packages, relative.as_posix()):
        claims.append("site")
    if claims:
        lines.append(f"    claimed by: {', '.join(claims)}")
    lines.extend(f"    {line}" for line in owned_lines(root, relative))
    return lines


def unit_of(
    root: Path, packages: tuple[Package, ...], path: str
) -> tuple[Package | None, str]:
    """The package *path* belongs to and the path inside it, or the root's unit.

    A path under no package is the workspace unit's, relative to the
    root; None when the root has no unit to speak of.
    """
    from livery.workshop._coverage_store import workspace_suite

    for package in packages:
        if path.startswith(package.path + "/"):
            return package, path[len(package.path) + 1 :]
    return workspace_suite(root) or _root_unit(root), path


def _root_unit(root: Path) -> Package:
    """The workspace unit for a root without its own tests directory."""
    from livery.workshop._categories import WORKSPACE

    return Package(
        directory=root, path=".", name="workspace", kind=WORKSPACE, depends=()
    )


def owned_lines(root: Path, relative: Path) -> list[str]:
    """What a managed file carries that the repository owns, one line each.

    A marked region is named with the lines its markers enclose. A file
    without one says nothing.
    """
    from livery.workshop import _regions

    path = root / relative
    if not path.is_file():
        return []
    text = path.read_text(encoding="utf-8", errors="replace")
    return [
        f"region {region.name}: lines {region.first} to {region.last}, yours to"
        " edit inside the markers; the render keeps it"
        for region in _regions.regions_in(text)
    ]


def _content_trees(root: Path) -> list[tuple[str, Path]]:
    """Each workspace package's shipped content tree, with its extension name."""
    from livery.workshop._packages import package_directories

    trees = []
    for directory in package_directories(root):
        src = directory / "src"
        if not src.is_dir():
            continue
        for content in sorted(src.rglob("content")):
            if not content.is_dir():
                continue
            if {"templates", "content"} & set(content.relative_to(src).parts[:-1]):
                continue  # a seed's own content tree, written at a birth
            extension = ".".join(content.parent.relative_to(src).parts)
            trees.append((extension, content))
    return trees


def content_lint(
    root: Path, *, fix: bool = False, files: frozenset[str] | None = None
) -> list[str]:
    """Extension content files missing their computed header; ``fix`` writes it.

    *files* keeps the lint to those root-relative files; None lints
    every content file.

    Only the workspace's own packages are linted: an installed
    extension's content is its home repository's to keep. Files without
    a comment syntax are exempt, and so are the fragment engine's
    templates under `content/root/` and `content/package/`, whose
    composed files carry headers of their own, and the seeds under
    `content/seeds/`, which become the workspace's own files.
    """
    from livery.workshop._seeds import SEEDS
    from livery.workshop._shipped_files import PACKAGE_CONTENT, ROOT_CONTENT

    problems = []
    for extension, content in _content_trees(root):
        for path in sorted(content.rglob("*")):
            if not path.is_file() or "__pycache__" in path.parts:
                continue
            if files is not None and path.relative_to(root).as_posix() not in files:
                continue
            # A template the fragment engine composes into a workspace file
            # carries that file's own header; this one would land in it.
            if path.relative_to(content).parts[0] in (
                ROOT_CONTENT,
                PACKAGE_CONTENT,
                SEEDS,
            ):
                continue
            style = comment_style(path)
            if not style:
                continue
            header = content_header(extension, style)
            if has_header(path, header):
                continue
            if fix:
                inject(path, header)
                problems.append(f"{path.relative_to(root).as_posix()}: header written")
            else:
                problems.append(
                    f"{path.relative_to(root).as_posix()}: missing its header"
                )
    return problems


@task(name="provenance")
def provenance_check(
    fix: Annotated[bool, doc("write the computed headers in place")] = False,
) -> None:
    """Check shipped extension content opens with its provenance header.

    Part of the gate. Nobody composes a header by hand: ``--fix``
    writes the computed text, and the render and emitters inject
    theirs into everything they write.
    """
    check_content(fix=fix)


def check_content(*, fix: bool = False, files: frozenset[str] | None = None) -> None:
    """The provenance check over the content files in scope; refuses a missing header.

    The engine behind `fm provenance` and the gate's check: *files*
    keeps it to those root-relative files, None to every content file.
    """
    root = workspace_root()
    if root is None:
        fail("no workspace: no workshop.toml above the working directory")
    findings = content_lint(root, fix=fix, files=files)
    for line in findings:
        print(f"  {line}")
    if findings and not fix:
        fail(
            "extension content is missing provenance headers: run"
            f" `{footman.prog()} check --fix` to write them"
        )
