"""Provenance: which channel owns a file, and where to edit it.

One classifier answers for any path; everything else serialises its
answer. ``fm explain <path>`` prints it. The templates carry their
own headers (parameterised, so ``copier update`` sees them as
template lines, never local edits) and the emitters open every
generated file with theirs, so the answer rides the file wherever
comments are possible. Materialised copies are never injected:
override detection depends on the copy staying byte-identical to
its source, so those files, and comment-hostile ones, are explain's
territory alone. Shipped layer content carries its header through
the provenance lint, whose ``--fix`` writes the computed text.
"""

from __future__ import annotations

import os
from pathlib import Path
from typing import Annotated

import livery.footman as footman
from livery.footman import Arg, ask, doc, fail, suggest, task
from livery.workshop._categories import (
    ChannelRule,
    Provenance,
    category_of,
    channel_of,
    register_channels,
)
from livery.workshop._layers import layer_names, workspace_root
from livery.workshop._packages import Package

#: The project render's managed names, judged by the drift gate. The
#: template tree is the truth; this list is the offline copy a wheel
#: instance can answer from, pinned against the tree by test.
PROJECT_RENDERED = (
    "pyproject.toml",
    "tasks.py",
    ".gitignore",
    ".gitattributes",
    ".vscode/settings.json",
    ".vscode/extensions.json",
)

#: Comment leaders by suffix, and by exact name for suffixless files.
#: A type absent from both tables cannot carry a header and is
#: explain's territory alone.
_BY_SUFFIX = {
    ".py": "#",
    ".toml": "#",
    ".yml": "#",
    ".yaml": "#",
    ".sh": "#",
    ".cfg": "#",
    ".ini": "#",
    ".md": "html",
}
_BY_NAME = {".gitignore": "#", ".gitattributes": "#", "CODEOWNERS": "#"}


def comment_style(path: Path) -> str:
    """The comment leader for *path*: ``#``, ``//``, ``html``, or empty.

    The editor's ``.vscode/settings.json`` is JSON with comments, the
    one JSON the render owns; every other JSON carries no header.
    """
    if path.name == "settings.json" and path.parent.name == ".vscode":
        return "//"
    return _BY_NAME.get(path.name, _BY_SUFFIX.get(path.suffix, ""))


#: Phrases that mark a header as machine-written, for refresh.
_MARKERS = (
    "the template channel",
    "the workshop from workshop.toml",
    "Seeded from",
    "layer content",
)


def format_header(lines: tuple[str, ...], style: str) -> str:
    """The header *lines* as one comment block in *style*."""
    if style == "html":
        body = "".join(f"     {line}\n" for line in lines[1:])
        return f"<!-- {lines[0]}\n{body}-->\n"
    return "".join(f"{style} {line}\n" for line in lines)


def generated_header(style: str) -> str:
    """The header every emitted artifact opens with."""
    prog = footman.prog()
    lines = (
        "Generated by the workshop from workshop.toml; the gate keeps",
        "it matching. Edit the contract (or the emitters) and run",
        f"`{prog} template.apply`; an edit here is drift.",
    )
    return format_header(lines, style)


def content_header(layer: str, style: str) -> str:
    """The header shipped layer content carries, lint-enforced."""
    lines = (
        f"Shipped as {layer} layer content, delivered to the workspace",
        "by the sync verb. Edit this copy in the layer and release it;",
        "an edited delivered copy is a local override, kept and named.",
    )
    return format_header(lines, style)


def _insertion_point(text: str, path: Path) -> int:
    """Where a header lands: after a shebang or markdown frontmatter."""
    if text.startswith("#!"):
        return text.find("\n") + 1
    if path.suffix == ".md" and text.startswith("---\n"):
        end = text.find("\n---\n", 4)
        if end != -1:
            return end + len("\n---\n")
    return 0


def inject(path: Path, header: str) -> None:
    """Open *path* with *header*, replacing a stale machine header."""
    text = path.read_text(encoding="utf-8")
    text = strip_header(text, path)
    at = _insertion_point(text, path)
    path.write_text(text[:at] + header + text[at:], encoding="utf-8", newline="\n")


def has_header(path: Path, header: str) -> bool:
    """Whether *path* already opens with *header* (shebang-tolerant)."""
    text = path.read_text(encoding="utf-8")
    at = _insertion_point(text, path)
    return text[at:].startswith(header)


def strip_header(text: str, path: Path) -> str:
    """*text* with a machine-written header removed, others kept."""
    at = _insertion_point(text, path)
    head, tail = text[:at], text[at:]
    style = comment_style(path)
    if style == "html":
        if tail.startswith("<!--") and "-->" in tail:
            block, _, rest = tail.partition("-->\n")
            if any(marker in block for marker in _MARKERS):
                return head + rest.lstrip("\n")
        return text
    lines = tail.splitlines(keepends=True)
    block_end = 0
    for line in lines:
        if line.startswith("#") and not line.startswith("#!"):
            block_end += 1
        else:
            break
    block = "".join(lines[:block_end])
    if any(marker in block for marker in _MARKERS):
        rest = "".join(lines[block_end:]).lstrip("\n")
        return head + rest
    return text


def _materialised(root: Path, relative: Path) -> Provenance | None:
    """The answer for a path the sync verb delivers, or None."""
    from livery.workshop._materialise import _is_link, _read_manifest

    prog = footman.prog()
    parts = relative.parts
    if parts[0] == ".workshop":
        if parts[1:2] == ("fragments",):
            return Provenance(
                "layer fragment",
                f"a mounted layer's content/fragments/{relative.name}",
                f"edit the layer's copy; `{prog} sync` rewrites this one wholesale",
            )
        # Everything else under .workshop is this checkout's own: the
        # tool receipts, the stub receipt, the linked binaries, a layer
        # home's composed templates. None of them has an edit path, and
        # calling them layer fragments was a lie the directory's older
        # shape made easy to tell.
        return Provenance(
            "checkout state",
            f"written by `{prog} sync` for this checkout alone",
            "nothing to edit here; delete it and the next sync writes it again",
        )
    if parts[0] == "CLAUDE.md" and len(parts) == 1:
        return Provenance(
            "sync stub",
            f"written by `{prog} sync` from the mounted layers' fragments",
            "edit CLAUDE.project.md, never this file",
        )
    if parts[0] != ".claude" or len(parts) < 2:
        return None
    if parts[1] in ("skills", "hooks") and len(parts) >= 3:
        home = root / ".claude" / parts[1]
        entry = home / parts[2]
        manifest = _read_manifest(home)
        if _is_link(entry) or parts[2] in manifest:
            return Provenance(
                "materialised",
                f"a mounted layer's content/{parts[1]}/{parts[2]}",
                "edit the layer's copy; an edit here becomes a local"
                " override on the next sync",
            )
        return Provenance(
            "local override" if _shipped(parts[1], parts[2]) else "yours",
            "this repository",
            "edit directly; it commits like any repo file",
        )
    if parts[1] == "settings.json":
        manifest = _read_manifest(root / ".claude")
        if "settings.json" in manifest:
            return Provenance(
                "materialised",
                "a mounted layer's content/settings.json",
                "edit the layer's copy; an edit here becomes a local"
                " override on the next sync",
            )
        return Provenance(
            "local override" if _shipped("", "settings.json") else "yours",
            "this repository",
            "edit directly; it commits like any repo file",
        )
    return None


def _shipped(subdir: str, name: str) -> bool:
    """Whether any mounted layer ships this content entry."""
    from livery.workshop._sync import _layer_content

    for layer in layer_names():
        content = _layer_content(layer)
        if content is None:
            continue
        candidate = content / subdir / name if subdir else content / name
        if candidate.exists():
            return True
    return False


def emitted_paths(root: Path) -> frozenset[str]:
    """The paths the workshop emitters write for *root*, the owners file included.

    One emission is a full render of every workflow, the site
    configuration, and the entry script; a caller classifying many
    paths computes this once and hands it to
    [livery.workshop._provenance.classify][].
    """
    from livery.workshop._ci_generate import generate
    from livery.workshop._governance import codeowners_file

    generated = set(generate(root))
    owners = codeowners_file(root)
    if owners is not None:
        generated.add(owners.path)
    return frozenset(generated)


def classify(
    root: Path, relative: Path, *, emitted: frozenset[str] | None = None
) -> Provenance:
    """The provenance of *relative* inside *root*; "yours" when no channel claims it.

    *relative* is taken lexically, never resolved: a materialised
    link classifies as the delivered entry it is, not as the wheel
    path it points into. *emitted* is the emitters' path set from
    [livery.workshop._provenance.emitted_paths][]; a caller with many
    paths passes one set rather than paying an emission per path.
    The answer comes from the channel registry, the builtin ladder
    below and whatever a layer registered beside it, highest rank
    first.
    """
    found = channel_of(root, relative, emitted=emitted)
    if found is not None:
        return found.provenance
    return Provenance("yours", "this repository", "edit directly")


def _rule_materialised(
    root: Path, relative: Path, emitted: frozenset[str] | None
) -> Provenance | None:
    del emitted
    return _materialised(root, relative)


def _rule_generated(
    root: Path, relative: Path, emitted: frozenset[str] | None
) -> Provenance | None:
    prog = footman.prog()
    generated = emitted_paths(root) if emitted is None else emitted
    if relative.as_posix() not in generated:
        return None
    return Provenance(
        "generated",
        "the workshop emitters, from workshop.toml",
        f"edit workshop.toml (or the emitters) and run `{prog} template.apply`",
    )


def _rule_rendered(
    root: Path, relative: Path, emitted: frozenset[str] | None
) -> Provenance | None:
    del emitted
    from livery.workshop._templates import template_source

    if relative.as_posix() not in PROJECT_RENDERED:
        return None
    prog = footman.prog()
    return Provenance(
        "rendered",
        f"the template channel ({template_source(root)}, project kind)",
        f"edit the template source and run `{prog} template.apply`",
    )


def _rule_seed(
    root: Path, relative: Path, emitted: frozenset[str] | None
) -> Provenance | None:
    del emitted
    from livery.workshop._templates import PROJECT_SEEDS, template_source

    if relative.as_posix() not in PROJECT_SEEDS:
        return None
    return Provenance(
        "seed",
        f"seeded at birth from the template channel ({template_source(root)})",
        "yours: edit directly; the template never rewrites it",
    )


def _rule_answers(
    root: Path, relative: Path, emitted: frozenset[str] | None
) -> Provenance | None:
    del root, emitted
    if relative.as_posix() != ".copier-answers.yml":
        return None
    prog = footman.prog()
    return Provenance(
        "receipts",
        "machine-managed identity and template provenance",
        f"never by hand; `{prog} new.package` and the update wave write it",
    )


def _rule_contract(
    root: Path, relative: Path, emitted: frozenset[str] | None
) -> Provenance | None:
    del root, emitted
    if relative.name != "workshop.toml":
        return None
    return Provenance(
        "contract",
        "the workspace contract, config-as-code",
        "edit directly and merge; governance applies itself on main",
    )


def _rule_environment(
    root: Path, relative: Path, emitted: frozenset[str] | None
) -> Provenance | None:
    del root, emitted
    if relative.as_posix() != ".repo.env":
        return None
    prog = footman.prog()
    return Provenance(
        "environment",
        "the committed rung of the env cascade",
        f"`{prog} env.set KEY --scope=repo`, or edit directly",
    )


def _rule_toolchain(
    root: Path, relative: Path, emitted: frozenset[str] | None
) -> Provenance | None:
    del root, emitted
    if relative.as_posix() != "uv.lock":
        return None
    return Provenance(
        "toolchain",
        "uv's lockfile",
        "`uv lock` (or the update wave); never by hand",
    )


def _rule_member(
    root: Path, relative: Path, emitted: frozenset[str] | None
) -> Provenance | None:
    """A package's own files: its changelog config, its receipts, its content."""
    del emitted
    from livery.workshop._templates import template_source

    if len(relative.parts) <= 2 or relative.parts[0] != "packages":
        return None
    prog = footman.prog()
    member = Path(*relative.parts[:2])
    rest = Path(*relative.parts[2:]).as_posix()
    if rest == "cliff.toml":
        return Provenance(
            "rendered",
            f"the template channel ({template_source(root)}, package-python kind)",
            f"edit the template source and run `{prog} template.apply`",
        )
    if rest == ".copier-answers.yml":
        return Provenance(
            "receipts",
            "machine-managed package identity",
            "never by hand; the render wrote it",
        )
    if rest == ".workshop-rendered":
        return Provenance(
            "receipts",
            "what the render wrote into this package for the checks' files",
            f"never by hand; `{prog} template.apply` keeps it",
        )
    if rest in (".clang-format", ".clang-tidy"):
        return Provenance(
            "rendered",
            "a check record's fragment for this package's kind",
            f"edit the record's fragment and run `{prog} template.apply`; a"
            " deeper file with InheritParentConfig carries this package's own lines",
        )
    if "/content/" in rest:
        return Provenance(
            "layer content",
            f"{member.as_posix()}: what this layer ships; the"
            " provenance lint keeps its header",
            f"edit directly here; `{prog} sync` delivers it",
        )
    return Provenance(
        "yours",
        f"{member.as_posix()}: the package's own file since its birth",
        "edit directly",
    )


# The builtin ladder as ranked rules: a layer registers its own beside
# them, at the rank that says where it stands.
register_channels(
    [
        ChannelRule("materialised", _rule_materialised, 100, "livery.workshop"),
        ChannelRule("generated", _rule_generated, 90, "livery.workshop"),
        ChannelRule("rendered", _rule_rendered, 80, "livery.workshop"),
        ChannelRule("seed", _rule_seed, 70, "livery.workshop"),
        ChannelRule("answers", _rule_answers, 60, "livery.workshop"),
        ChannelRule("contract", _rule_contract, 50, "livery.workshop"),
        ChannelRule("environment", _rule_environment, 40, "livery.workshop"),
        ChannelRule("toolchain", _rule_toolchain, 30, "livery.workshop"),
        ChannelRule("member", _rule_member, 20, "livery.workshop"),
    ]
)


def _tracked_paths() -> list[str]:
    """Git-tracked paths, the completion surface for explain."""
    root = workspace_root()
    if root is None:
        return []
    from livery.toolroom import tools

    listing = tools.git.opts(cwd=root, nofail=True, recorded=False)("ls-files")
    return listing.stdout.splitlines()


@task
def explain(
    path: Annotated[
        Arg[str],
        ask(),
        suggest(_tracked_paths, strict=False),
        doc("the file to explain, relative to the workspace root"),
    ] = "",
) -> None:
    """Name the channel that owns a file, its source, and the edit path.

    Every answer has the same three lines; a file no channel claims is
    yours, which is the honest default, not an error.
    """
    if not path:
        fail(f"name a file: `{footman.prog()} explain pyproject.toml`")
    root = workspace_root()
    if root is None:
        fail("no workspace: no workshop.toml above the working directory")
    raw = Path(path)
    if raw.is_absolute():
        try:
            raw = raw.relative_to(root)
        except ValueError:
            fail(f"{path} is outside this workspace")
    relative = Path(os.path.normpath(str(raw)))
    if not relative.parts or relative.parts[0] == "..":
        fail(f"{path} is outside this workspace")
    for line in describe(root, relative):
        print(line)


def describe(root: Path, relative: Path) -> list[str]:
    """The lines ``fm explain`` prints for *relative*: category, channel, claims."""
    from livery.workshop._docs import site_reads
    from livery.workshop._packages import discover_packages

    packages = discover_packages(root) if (root / "packages").is_dir() else ()
    unit, inside = unit_of(root, packages, relative.as_posix())
    lines = [f"  {relative.as_posix()}"]
    if unit is not None:
        category = category_of(unit, inside)
        lines.append(f"    category: {category.name} ({category.supplier})")
    found = channel_of(root, relative)
    answer = found.provenance if found is not None else classify(root, relative)
    supplier = found.supplier if found is not None else "livery.workshop"
    lines.append(f"    channel: {answer.channel} ({supplier})")
    lines.append(f"    source: {answer.source}")
    lines.append(f"    edit: {answer.edit}")
    from livery.workshop._checks import claimants

    claims = list(claimants(unit, inside)) if unit is not None else []
    if site_reads(root, packages, relative.as_posix()):
        claims.append("site")
    if claims:
        lines.append(f"    claimed by: {', '.join(claims)}")
    lines.extend(f"    {line}" for line in owned_lines(root, relative))
    return lines


def unit_of(
    root: Path, packages: tuple[Package, ...], path: str
) -> tuple[Package | None, str]:
    """The package *path* belongs to and the path inside it, or the root's unit.

    A path under no package is the workspace unit's, relative to the
    root; None when the root has no unit to speak of.
    """
    from livery.workshop._coverage_store import workspace_suite

    for package in packages:
        if path.startswith(package.path + "/"):
            return package, path[len(package.path) + 1 :]
    return workspace_suite(root) or _root_unit(root), path


def _root_unit(root: Path) -> Package:
    """The workspace unit for a root without its own tests directory."""
    from livery.workshop._categories import WORKSPACE

    return Package(
        directory=root, path=".", name="workspace", kind=WORKSPACE, depends=()
    )


def owned_lines(root: Path, relative: Path) -> list[str]:
    """What a managed file carries that the repository owns, one line each.

    A marked region is named with the lines its markers enclose; a
    tail file names the line the render's bytes end on. A file with
    neither says nothing.
    """
    from livery.workshop import _regions
    from livery.workshop._templates import TAIL_FILES

    posix = relative.as_posix()
    path = root / relative
    if not path.is_file():
        return []
    if posix in TAIL_FILES:
        return [
            "yours: the render owns this file's first lines, as many as it"
            " renders; your own lines follow them"
        ]
    text = path.read_text(encoding="utf-8", errors="replace")
    return [
        f"region {region.name}: lines {region.first} to {region.last}, yours to"
        " edit inside the markers; the render keeps it"
        for region in _regions.regions_in(text)
    ]


def _content_trees(root: Path) -> list[tuple[str, Path]]:
    """Each workspace package's shipped content tree, with its layer name."""
    trees = []
    for src in sorted(root.glob("packages/*/src")):
        for content in sorted(src.rglob("content")):
            if not content.is_dir():
                continue
            if "templates" in content.relative_to(src).parts:
                continue  # a template kind's content seeds render later
            layer = ".".join(content.parent.relative_to(src).parts)
            trees.append((layer, content))
    return trees


def content_lint(root: Path, *, fix: bool = False) -> list[str]:
    """Layer content files missing their computed header; ``fix`` writes it.

    Only the workspace's own packages are linted: an installed
    layer's content is its home repository's to keep. Files without
    a comment syntax are exempt; explain still answers for them.
    """
    problems = []
    for layer, content in _content_trees(root):
        for path in sorted(content.rglob("*")):
            if not path.is_file() or "__pycache__" in path.parts:
                continue
            style = comment_style(path)
            if not style:
                continue
            header = content_header(layer, style)
            if has_header(path, header):
                continue
            if fix:
                inject(path, header)
                problems.append(f"{path.relative_to(root).as_posix()}: header written")
            else:
                problems.append(
                    f"{path.relative_to(root).as_posix()}: missing its header"
                )
    return problems


@task(name="provenance")
def provenance_check(
    fix: Annotated[bool, doc("write the computed headers in place")] = False,
) -> None:
    """Check shipped layer content opens with its provenance header.

    Part of the gate. Nobody composes a header by hand: ``--fix``
    writes the computed text, and the render and emitters inject
    theirs into everything they write.
    """
    root = workspace_root()
    if root is None:
        fail("no workspace: no workshop.toml above the working directory")
    findings = content_lint(root, fix=fix)
    for line in findings:
        print(f"  {line}")
    if findings and not fix:
        fail(
            "layer content is missing provenance headers: run"
            f" `{footman.prog()} check --fix` to write them"
        )
